### ISSUE TITLE
support to get/set segment_leaderboard_opt_out on activities

### ISSUE THREAD

**Issue by arkarkark** [stravalib/stravalib#102]
Similar to https://github.com/strava/go.strava/issues/16
If/when the API supports it I don't mind making a PR for this library.

It doesn't look like the api supports getting/setting the new `segment_leaderboard_opt_out` attribute on [activities](https://strava.github.io/api/v3/activities/). Do you know if/when support for that will be added?

I found the name by looking at what the front end does, when it PUTs to `https://www.strava.com/athlete/training_activities/xxxxxxxx`

**Comment by hozn** [comment]
Good question! - Yeah, typically the API supports it when they decide they want to implement it in their mobile apps.   I don't know if they really have a roadmap for improvements to their API.  I know the changes often catch us by surprise, though maybe I'm just not subscribed to the right mailing list to get notified of those :)

**Comment by arkarkark** [comment]
Thanks, the mobile app seems to support it (at least iOS does) I haven't gone as far as trying to sniff the network traffic to work out what's going on...

**Comment by timthelion** [comment]
I think this is supported by strava now. Woke up this morning to a bunch of sentry logs that look like:

````
No such attribute leaderboard_opt_out on entity <Activity id=xxxxxx name='xxxxx' resource_state=None>
````
