### ISSUE TITLE
Rate Limit problems

### ISSUE THREAD

**Issue by 35944** [stravalib/stravalib#108]
Hi,

When the rate limit is reached, a internal server error (500) is popping up, stating a DeadlineExceededError:
DeadlineExceededError: The overall deadline for responding to the HTTP request was exceeded.

It traces back to __call__ (/lib/stravalib/util/limiter.py:64), and my guess is it is related to this part:
                    # Wait the difference between timeframe and the oldest request.
                    td = self.timeframe - delta
                    sleeptime = hasattr(td, 'total_seconds') and td.total_seconds() or total_seconds(td)
                    self.log.debug("Rate limit triggered; sleeping for {0}".format(sleeptime))
                    time.sleep(sleeptime)

Could it be that the time.sleep(sleeptime) is causing the DeadlineExceededError?

**Comment by hozn** [comment]
I don't want to say that is not possible, but the intent of that sleep code is to sleep between different requests.  Admittedly, though, I've not played recently with exceeding rate limit; I have the sense that the Strava response codes / headers / etc. have gotten more sophisticated.  We really need a more responsive / less-naive version of the rate limiter.
