### ISSUE TITLE
Optional wait/sleep functionality in XRateLimitRule

### ISSUE THREAD

**Issue by piotr-kubica** [stravalib/stravalib#125]
> It would be nice to have some (optional) wait/sleep functionality in XRateLimitRule, similar to that in the existing RateLimitRule. End users of a 3rd party app using Strava would find it more tolerable to have multiple latencies of a few seconds each instead of single latencies of potentially several minutes.

As mentioned by [jsamoocha](https://github.com/hozn/stravalib/pull/121) in #121

**Comment by jsamoocha** [comment]
See #124  :-)

**Comment by jsamoocha** [comment]
Resolved by #124
