### ISSUE TITLE
Switch to using Marshmallow for serialization

### ISSUE THREAD

**Issue by hozn** [stravalib/stravalib#135]
[Marshmallow](https://marshmallow.readthedocs.io/en/latest/) would make for a more universal and cleaner solution to deserializing (and serializing) the data from Strava.

Advantages:
- Less magical use of class vs. instance attrs
- (relatedly) better IDE integration (type hinting)

Disadvantages / Mismatches:
- Concepts like tracking whether attrs exist in detailed or summary views wouldn't be something that worked out-of-the-box.  But then, it's not something we've ever used anyway.
- We might lose some of the debug/warning messages about missing attrs (or new attrs) which are helpful now in knowing when we need to tweak the model.  But probably not hard to override/hook these in, should we really need them.  Usually they just annoy people anyway.

This would be a big, breaking change.

**Comment by jsamoocha** [comment]
Resolved by #350
