### ISSUE TITLE
Drop python 2 support

### ISSUE THREAD

**Issue by hozn** [stravalib/stravalib#136]
For version 2.0, we'll drop support for python 2, so that we can use native python type hinting and other features in python 3.  It's time.

Whether we want to rename the library or just continue a 0.x branch for python 2, is unclear at this time.  Hopefully we can just have version >= 2.x require python 3.6+  and version 1.x remains compatible with python 2.7+. 

1.x would only get bugfixes going forward.

**Comment by jsamoocha** [comment]
Python2 support is dropped in release v1.0.0
