### ISSUE TITLE
stravalib depends on pip internal functions 

### ISSUE THREAD

**Issue by paulte** [stravalib/stravalib#149]
It looks like stravalib/setup.py is relying on parse_requirements to be a stable / exposed interface.

There's references that the pip module doesn't support this type of use:
https://github.com/pypa/pip/issues/2286

Testing stravalib with python3.5, pip 10.0.0 in a clean virtualenv gives the following

```
$ virtualenv  -p $(which python3) venv && . venv/bin/activate
$ python -V
Python 3.5.2
$ pip -V
pip 10.0.0 from /Users/teasdep/python/strava/venv/lib/python3.5/site-packages/pip (python 3.5)
teasdep@tiny $ pip install stravalib
Collecting stravalib
  Using cached https://files.pythonhosted.org/packages/76/6a/13027ce4f6141bbf314f1744e353cdee6ad2b8411e713b13b6ffc2fcf460/stravalib-0.9.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4_/wy9qvpvn0sz5t91r3p1ylsd00000gn/T/pip-install-sb1gln78/stravalib/setup.py", line 6, in <module>
        from pip.req import parse_requirements
    ImportError: No module named 'pip.req'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4_/wy9qvpvn0sz5t91r3p1ylsd00000gn/T/pip-install-sb1gln78/stravalib/
```

**Comment by hozn** [comment]
Thanks for letting me know!  I'll figure out the more official way to achieve this.

**Comment by paulte** [comment]
This should do it:

https://github.com/hozn/stravalib/pull/150

**Comment by MurielMauch** [comment]
Another solution for this issue can be seen here <https://stackoverflow.com/questions/25192794/no-module-named-pip-req> and it is as it follows:

try: # for pip >= 10
    from pip._internal.req import parse_requirements
except ImportError: # for pip <= 9.0.3
    from pip.req import parse_requirements

I'm not sure though if it's the best option, but it worked locally.

**Comment by paulte** [comment]
From a bit of digging around at the time, the consensus I reached was that pip provided  functions shouldn’t be seen as a stable / external interface layer for re-use.  Looks to be  a common misunderstanding/issue for a number of python modules over time as the pip module has evolved.

**Comment by zefoo** [comment]
I did pip install pip==9.0.3 – that solved it. I second @paulte, pip 10 isn't too stable from what I found.
