### ISSUE TITLE
How to get segment from an activity stream?

### ISSUE THREAD

**Issue by zefoo** [stravalib/stravalib#151]
First, great library – glad I found this! Thank ya'll.

1. I want to get the segment ID from a specific time that I pull via activity stream of an auth'd user. I don't see a way to pull the segment via an activity stream (it'd be great if that was a type provided by API). Is this possible?

2. I believe I can pull all segment efforts per https://groups.google.com/forum/#!searchin/strava-api/segments$20from$20streams%7Csort:date/strava-api/XtqpKBssXuI/hi5SgcWKmhEJ – but I'm not sure how to do this? It's possible this may have changed since that thread was from 4 years ago. The bigger question is, is it possible to pull any streams from users who didn't auth the app? I'm mostly curious on pulling data from other users and cross referencing. 

I'm really only interested in my question to 1 so I can use the segment ID to pull a stream from other users who have recently ridden a segment... but it's possible none of this is doable. 

Thank you!

**Comment by 35944** [comment]
Hi,

I'm not sure what your intent is with your first question. What do you mean with a segment ID from a specific time?

Second. This might help:
`activity_segments = client.get_activity(567288259, include_all_efforts="True").segment_efforts`
replace 567288259 with the activity you'd like to get the segments from.

If you then run a for loop over the segments, you can get segment information. If you, for instance, want the segment id:

`for segment in activity_segments:`
`    segment_id = segment.segment.id`

Cheers,
Pieter
