### ISSUE TITLE
RateLimitExceeded raised with wrong parameters

### ISSUE THREAD

**Issue by sander48k** [stravalib/stravalib#154]
When the RateLimitExceeded exception is raised, its limit and timeout parameters seem to be swapped. E.g. limit = 900, timeout = 600 when the short limit of the DefaultRateLimiter has exceeded.

I think, in `XRateLimitRule._check_limit_rates`, `_raise_rate_limit_exception` is called with parameters in the wrong order.

**Comment by hozn** [comment]
Thanks for posting this; I'll take a look!

**Comment by lwasser** [comment]
closing this as it was addressed here given stravalib's recent updates! https://github.com/stravalib/stravalib/pull/446
