### ISSUE TITLE
update_activity with gear_id='none' works for rides but not for runs

### ISSUE THREAD

**Issue by enicklas** [stravalib/stravalib#160]
According to https://developers.strava.com/docs/reference/#api-models-UpdatableActivity, setting the gear_id to 'none' should clear gears from the activity on an update. This works fine via stravalib's update_activity for rides, but not for runs (the gear is kept without changes). I have not checked with other sports types

Not sure if this is a bug in stravalib or the strava API itself.

Thanks a lot for your great work, stravalib is awesome. Please let me know if I can help further with debugging this,
Eike

Code to reproduce:
result = strava_client.create_activity('test activity', 'run', datetime(2018, 10, 8, 21, 18, 00), 100, 'a test', 4)
# default gear is used

activity_id = result.id
strava_client.update_activity(activity_id, 'updated test activity', 'run', True, False, False, 'none', 'an update')
# gear should be cleared but is not

**Comment by lwasser** [comment]
hey there @enicklas i'm going through and looking at old issues to see if they still persist given the big changes we've made to the stravalib api. this one is 5 years old - phew! 

is this still a problem that you are encountering?  or do you think we can close this issue given the updates to our api?

**Comment by enicklas** [comment]
Hi @lwasser 

I am currently not actively using stravalib, so I cannot really anwer your question ;-)

closling the issue. If I run into it again, I can re- open

**Comment by lwasser** [comment]
@enicklas thank you for the reply - i'll go ahead and close the issue but if you happen to use stravalib again and have questions please feel free to create a new issue! All the best ✨
