### ISSUE TITLE
Segments on route

### ISSUE THREAD

**Issue by ghn** [stravalib/stravalib#161]
Hello,

Is it already planned to add `segments` in the `Route` model ? https://github.com/hozn/stravalib/blob/master/stravalib/model.py#L1099
or shall I strart doing it? If so, any hint to help me get started?
Thanks

**Comment by lwasser** [comment]
hey @ghn 👋 i'm going through and cleanup up old issues! i wondered if you had tried this with our new API that is derived from the strava swagger.json ? there is some segment support in [our current Route object](https://github.com/stravalib/stravalib/blob/main/src/stravalib/model.py#L1189). Please let us know if this works for you / or if we can close this issue!

**Comment by ghn** [comment]
Hey :wave: , no I haven't since not using this lib these days.
