### ISSUE TITLE
stravalib.exc.AccessUnauthorized error

### ISSUE THREAD

**Issue by fabthegreat** [stravalib/stravalib#170]
Hello,

Thanks for this promising API!

My code is quite simple:
```
from stravalib import Client

client = Client('8***7')
athlete = client.get_athlete() 

print("Hello, {}. I know your email is {}".format(athlete.firstname, athlete.email))

friends = client.get_athlete_friends()
      
for f in friends:
    print('hello')
```

first print for athlete firstname and email work fine but for friends it returns:
`stravalib.exc.AccessUnauthorized: Unauthorized: Authorization Error: []`

How to solve this?

Thanks

**Comment by alasspri** [comment]
Doesn't look like that is available any more. 

The code is calling the following route: `'/athletes/{id}/friends'` and references http://strava.github.io/api/v3/follow/#friends as documentation. However I can't see any reference to it in the playground or the API docs: https://developers.strava.com/playground/

Strangely can't see any deprecation notice in the changeling either.

**Comment by dongbum** [comment]
I programmed like @fabthegreat 's code. But I can't access friends/followers list, too.
Is unusable this feature? If so, need to update API documentation as soon as posible.

**Comment by hozn** [comment]
Hi all -- sorry for the silence on this.  Yes, indeed, it appears this was removed from the Strava API -- presumably along with all the other removals from big privacy refactor.

I'll leave this open as a documentation issue.

**Comment by dongbum** [comment]
@hozn Thanks to reply.
I suggest, how about add mark as 'deprecated' in documentation? ( https://pythonhosted.org/stravalib/usage/athletes.html#friends-and-followers )

Because most people read the documentation first. And they will find this issue page after find problem.
