### ISSUE TITLE
Documentation on https://pythonhosted.org/stravalib/ is lagging behind current version

### ISSUE THREAD

**Issue by obscurerichard** [stravalib/stravalib#175]
The documentation on https://pythonhosted.org/stravalib/ is for 0.6.5 but the current version is 0.10.2. Major changes in authentication have happened since then. Could you update the pythonhosted docs please?

**Comment by jsamoocha** [comment]
Docs are now at https://stravalib.readthedocs.io/en/latest/

**Comment by obscurerichard** [comment]
Thank you @jsamoocha !

I'm about to submit another issue & pull request 😉
