### ISSUE TITLE
Allowing multiple scopes

### ISSUE THREAD

**Issue by inspiran** [stravalib/stravalib#181]
Currently it seems to be not possible to pass multiple scopes to the authorization url.  An example use case is if you want to retrieve the gear of an athlete (profile:read_all) while also having access to their private activities (activity:read_all).

Is this by design or should the lib allow multiple scopes?   Is there perhaps a work around?

**Comment by alasspri** [comment]
I think you can pass a list of multiple scopes, as when you do they are all concatenated to the same string for the URL https://github.com/hozn/stravalib/blob/5500ebc39e0bf4706bb1ca4c27b25e56becaaa5f/stravalib/protocol.py#L93

e.g. 
`url = client.authorization_url(client_id=current_app.config['STRAVA_CLIENT_ID'],
                                   redirect_uri=redirect_uri,
                                   scope=['activity:read_all', 'profile:read_all'])`
