### ISSUE TITLE
from_dict() throws exception when parsing output from to_dict()

### ISSUE THREAD

**Issue by oliverkurth** [stravalib/stravalib#194]
I am trying to save output of `to_dict` , converted to json format, and then load it later. This fails.

This is how the output is saved:
```
    activities = client.get_activities(limit=200)
    for activity in activities:
        with open(os.path.join(activities_dir, '{}.json'.format(activity.id)), 'w') as f:
            json.dump(activity.to_dict(), f)
```

And this is how it's loaded again:

```
        with open(os.path.join(activities_dir, '{}.json'.format(id)), 'r') as f:
            d = json.load(f)
        activity = stravalib.model.Activity()
        activity.from_dict(d)
```

This throws an exception:
```
  File "/home/vmware/strava-locs/locs/locs.py", line 111, in load_activities
    activity.from_dict(d)
  File "/usr/local/lib/python2.7/dist-packages/stravalib/model.py", line 63, in from_dict
    setattr(self, k, v)
  File "/usr/local/lib/python2.7/dist-packages/stravalib/attributes.py", line 57, in __set__
    self.data[obj] = self.unmarshal(val)
  File "/usr/local/lib/python2.7/dist-packages/stravalib/attributes.py", line 201, in unmarshal
    tzname = v.split(' ', 1)[1]
IndexError: list index out of range
```

The reason is that the timezone string was modified from `"(GMT-08:00) America/Los_Angeles"` to `"America/Los_Angeles"` when saved, but on rereading the former format is expected. See https://github.com/hozn/stravalib/blob/master/stravalib/attributes.py#L194 .

Later on, after ignoring the above error by just unsetting `timezone`, there is an error when rereading `timedelta` values. The value is saved as a string in the format "hh:mm:ss", but on rereading an integer is expected, see https://github.com/hozn/stravalib/blob/master/stravalib/attributes.py#L223

**Comment by lwasser** [comment]
this was fixed via https://github.com/stravalib/stravalib/pull/195 @oliverkurth thanks for the PR. i think this issue just never got closed. i'm closing it now!! 🚀
