### ISSUE TITLE
Getting `DetailedAthlete` is there a way?

### ISSUE THREAD

**Issue by mrpbennett** [stravalib/stravalib#211]
How. can I get access to the `detailedAthlete`? I want to gain access to FTP,

**Comment by rotti** [comment]
https://developers.strava.com/docs/reference/#api-Athletes-getStats

**Comment by lwasser** [comment]
hey @mrpbennett 👋 i'm going through old issues and noticed this one. We have implemented a signiicant update to our API. i'm curious - if this issue still a problem for you? And if it is, can you kindly provide a reproducible code segment that helps us understand what you've tried and what data you're trying to access?

thank you!

if i don't hear from you in a week, given this is a several year old issue i'll close it. but you can also open a new issue after trying out our new api!!

**Comment by lwasser** [comment]
ok closing this given no response. please reopen if you have any concerns or run into this issue again!
