### ISSUE TITLE
Setup Ci to run tests on pr's - can anyone help me understand how to run tests please? nosetest-3

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#225]
If we add CI to run tests on every pr, it will be easier to determine whether new pr's are acceptable or need work. It will be easy to do this with GitHub actions.

**Comment by lwasser** [comment]
hey y'all - i'm trying to get the test suite to run so i can ensure tests run on all pr's and also to ensure i' haven't broken anything. i'm used to using pytest and am trying to understand nosetest. The readme says to run `nosetests-3`

i tried to install nose `pip install nose` and that command doesn't seem available. i'm running python 3 on a mac. Any guidance to help me get going with this test suite approach is great appreciated. once i can get this running i can setup CI for it to run on all pr's and i can update instructions to run tests locally. many thanks.

**Comment by hozn** [comment]
Hmm, no immediate thoughts, but I'd love to get rid of nosetests here.  This really predates purest being the standard.  Maybe that's something I can do this week. I don't expect it will be terribly hard to switch over; it may even just work, but I suspect that we'll need to convert some class setup/teardown fixtures to proper pytest fixtures.

**Comment by lwasser** [comment]
hey @hozn thanks! that would be great. i managed to get the test suite to run but am getting a lot of errors. i'm familiar with pytest. 

i setup a dummy strava account and we could in theory setup secrets (i think) for the access token and activity id to make this part work via CI. Using pytest would be great.

**Comment by jsamoocha** [comment]
Closing this issue as we have unit - and integration tests in CI now.
