### ISSUE TITLE
several syntax issues in setup.py and conf.py 

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#228]
@yihong0618 identified some syntax issues in these two files  see:

* https://github.com/hozn/stravalib/pull/224#discussion_r760743582
* https://github.com/hozn/stravalib/pull/224#discussion_r760743949

It could be good to address these in a separate PR vs the really big one open now about documentation. @yihong0618 feel free to submit a PR!

**Comment by yihong0618** [comment]
Cool.

**Comment by lwasser** [comment]
@yihong0618 i think we can close this now that i've overhauled the build and removed setup.py  I am going to close it but if you disagree / think there are still things to fix please do reopen!! thank you!
