### ISSUE TITLE
Delete activity using stravalib.client.Client.delete_activity

### ISSUE THREAD

**Issue by huaminghuangtw** [stravalib/stravalib#238]
I tried to delete a specific activity via `stravalib.client.Client.delete_activity` but I got:

> stravalib.exc.AccessUnauthorized: Unauthorized: Authorization Error: [{'resource': 'Application', 'field': 'internal', 'code': 'invalid'}]

I set the scope to `read,read_all,profile:read_all,profile:write,activity:read,activity:read_all,activity:write`, which I believe should be enough for the activity deletion. What could be wrong?

**Comment by futureshape** [comment]
There hasn't been a "delete activity" endpoint on the official Strava API since 2017: https://developers.strava.com/docs/changelog/#january-17-2017

I believe this method should be removed from this library

@huaminghuangtw as a workaround, you may wish to explore https://github.com/pR0Ps/stravaweblib which uses some additional "unofficial" ways of integrating with Strava.

**Comment by lwasser** [comment]
hi there @huaminghuangtw @futureshape 👋 i'm going through and cleaning up old issues. 

i do see the [delete_activity method](https://github.com/stravalib/stravalib/blob/main/src/stravalib/client.py#L947)  in our current APIl but i don't see it coming from the strava_model.py generated from the strava swagger json output. 

i'm wondering - @jsamoocha is this a method that we should delete from our library? i haven't actually tested this yet but this could be a valid issue that we might consider addressing if so?  or is there a backstory to keeping that method in the client module that i might be missing?

**Comment by lwasser** [comment]
for now i'm labeling this as a bug but please note i haven't actually tested anything yet!

**Comment by jsamoocha** [comment]
If the Strava API doesn't support this endpoint and returns an error, this is definitely a bug (which will be resolved by simply removing the `delete_activity()` method at our end.

**Comment by lwasser** [comment]
ok i can test this one and submit a small PR if removing the method is the best path forward. i'll also go through and make the other issues as bugs so we know these are things we want to chip away at! thanks!

**Comment by lwasser** [comment]
ok i just tested this and can confirm that locally it returns this error:

```
 client.delete_activity(id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/leahawasser/Documents/GitHub/stravalib/src/stravalib/client.py", line 958, in delete_activity
    self.protocol.delete("/activities/{id}", id=activity_id)
  File "/Users/leahawasser/Documents/GitHub/stravalib/src/stravalib/protocol.py", line 524, in delete
    return self._request(
  File "/Users/leahawasser/Documents/GitHub/stravalib/src/stravalib/protocol.py", line 325, in _request
    self._handle_protocol_error(raw)
  File "/Users/leahawasser/Documents/GitHub/stravalib/src/stravalib/protocol.py", line 369, in _handle_protocol_error
    raise exc.AccessUnauthorized(msg, response=response)
stravalib.exc.AccessUnauthorized: Unauthorized: Authorization Error: [{'resource': 'Application', 'field': 'internal', 'code': 'invalid'}]
```

i can open a PR to remove this method given it's documented to be no longer supported and is returning an invalid code / authroization error.
