### ISSUE TITLE
Permission to access pypi / setup release / push action and semantic versioning

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#244]
hi @hozn are you comfortable with giving me super power access to this repo to add secrets and such? And also with potentially sharing pypi credentials so I can setup an action to release and push there?

If you are you could email me at leah at pyopensci.org . i'm happy to help move things along here and to continue to contribute where I can! i think this package is really fantastic and i'd like to see it grow and become stable with a small maintenance team supporting it. 

I am working on a project now called [pyopensci](https://www.pyopensci.org) full time. the goal is to support maintainers working on projects like this.

**Comment by hozn** [comment]
Hi @lwasser  -- yes, I'm happy to do that.  I'm unsure how to grant additional privs in github, but I'll reach out by email and we can coordinate that + pypi.

**Comment by lwasser** [comment]
closing this as We have this working now in CI and I have authentication for both pypi and test pypi. thank you @hozn for trusting  us all to work on this
