### ISSUE TITLE
DEV: Move stravalib to setup.cfg and pyproject.toml

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#251]
Modern python packaging is moving away from setup.py files and to setup.cfg and toml files. I think ultimately everything will be in the toml files. As a baby step, I will make that transition in a single PR to a more modern package structure. 

More info on this here: http://ivory.idyll.org/blog/2021-transition-to-pyproject.toml-example.html

**Comment by lwasser** [comment]
hey @yihong0618 @jsamoocha @hozn can you please try installing stravalib locally from pypi test?

`pip install -i https://test.pypi.org/simple/ stravalib` 

and see if you run into any issues?

Its weird, it seems to be ok when i use it in a pip envt but i ran into an issues installing from pip into a conda environment. it used to install just fine in a conda envt so i am wondering if i broke something. none of the requirements are pinned in this test release. 

Also do we need `six` if we drop python 2.x?

``
(base) leahawasser@leahs-MacBook-Pro strava-for-lyfe % conda activate strava
(strava) leahawasser@leahs-MacBook-Pro strava-for-lyfe % pip install -i https://test.pypi.org/simple/ stravalib
Looking in indexes: https://test.pypi.org/simple/
Collecting stravalib
  Downloading https://test-files.pythonhosted.org/packages/67/1e/2e2c8d8d44f1c18edb0ca713eb674ecc796bb5b01cd3e00fca558ad6574a/stravalib-0.11.0.post6-py3-none-any.whl (111 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.9/111.9 kB 2.2 MB/s eta 0:00:00
Collecting arrow
  Downloading https://test-files.pythonhosted.org/packages/57/be/db25f7bd8f0e40cd57d80497c0cc298b50e24b3160f5bdf1a5ac4b2e448a/arrow-0.7.0.tar.gz (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.4/75.4 kB 2.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /Users/leahawasser/opt/miniconda3/envs/strava/lib/python3.8/site-packages (from stravalib) (1.16.0)
Requirement already satisfied: pytz in /Users/leahawasser/opt/miniconda3/envs/strava/lib/python3.8/site-packages (from stravalib) (2022.6)
Requirement already satisfied: requests in /Users/leahawasser/opt/miniconda3/envs/strava/lib/python3.8/site-packages (from stravalib) (2.28.1)
Collecting units
  Downloading https://test-files.pythonhosted.org/packages/80/9a/4fd8f45313305a9db67084fc4e377b8eaa403905b08f1f32c3ff917a7310/Units-1.0-py3-none-any.whl (6.6 kB)
Requirement already satisfied: python-dateutil in /Users/leahawasser/opt/miniconda3/envs/strava/lib/python3.8/site-packages (from arrow->stravalib) (2.8.2)
Requirement already satisfied: charset-normalizer<3,>=2 in /Users/leahawasser/opt/miniconda3/envs/strava/lib/python3.8/site-packages (from requests->stravalib) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/leahawasser/opt/miniconda3/envs/strava/lib/python3.8/site-packages (from requests->stravalib) (1.26.11)
Requirement already satisfied: certifi>=2017.4.17 in /Users/leahawasser/opt/miniconda3/envs/strava/lib/python3.8/site-packages (from requests->stravalib) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in /Users/leahawasser/opt/miniconda3/envs/strava/lib/python3.8/site-packages (from requests->stravalib) (3.4)
INFO: pip is looking at multiple versions of six to determine which version is compatible with other requirements. This could take a while.
Collecting six
  Downloading https://test-files.pythonhosted.org/packages/b3/b2/238e2590826bfdd113244a40d9d3eb26918bd798fc187e2360a8367068db/six-1.10.0.tar.gz (29 kB)
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of requests to determine which version is compatible with other requirements. This could take a while.
Collecting requests
  Downloading https://test-files.pythonhosted.org/packages/6d/00/8ed1b6ea43b10bfe28d08e6af29fd6aa5d8dab5e45ead9394a6268a2d2ec/requests-2.5.4.1-py2.py3-none-any.whl (468 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 kB 9.6 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of pytz to determine which version is compatible with other requirements. This could take a while.
Collecting pytz
  Downloading https://test-files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl (510 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.0/511.0 kB 17.2 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of arrow to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of stravalib to determine which version is compatible with other requirements. This could take a while.
Collecting stravalib
  Downloading https://test-files.pythonhosted.org/packages/d7/5d/e9ded6a295528a77901697e94fedc2841a256964999959975c58dbd81921/stravalib-0.10.0.tar.gz (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.8/89.8 kB 3.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement sympy (from units) (from versions: none)
ERROR: No matching distribution found for sympy
```

**Comment by jsamoocha** [comment]
I used pipenv for a change, and the installation had no (visible) issues.

**Comment by lwasser** [comment]
THANK YOU!  @jsamoocha
