### ISSUE TITLE
flake8 error seems not make `CI` failed

### ISSUE THREAD

**Issue by yihong0618** [stravalib/stravalib#252]
![image](https://user-images.githubusercontent.com/15976103/201476032-07b94487-944f-4d27-b06d-5dee8383b739.png)

please check: https://github.com/stravalib/stravalib/actions/runs/3443349681/jobs/5744790434

**Comment by lwasser** [comment]
Ahhh yes, so to merge we will have to fix the code locally. I spent a lot of time cleaning up flake8 issues but it looks like there are some new ones. this just ensure that we are following PEP 8 guidelines. Oh but some of that is coming from the docs. I can work on this once i get the setup install version stuff fixed @yihong0618 Is this preventing an existing PR from being merged? I could potentially fix those things in that pr too as a quick fix.  OR you could if you have time?

**Comment by yihong0618** [comment]
can we change the lint things to `black` and `isort` too?
that will be easy to use.

**Comment by jsamoocha** [comment]
I chose (based on the example starter workflow) to only let flake8 fail the CI build on syntax errors and undeclared variables. All other flake8 issues will be logged as warnings but not fail the build. This makes sure we will not accidentally ship code with syntax errors if that code happens to be not imported in any of the tests.

If we want to push for consistency in formatting, I'm not against adding black.

**Comment by lwasser** [comment]
I'm a big fan of black and i think isort sounds great too - i know a lot of packages use it now.  

we could setup a precommit hook for black, isort and flake 8. It would be optional to run locally but for us  as consistent maintainers it would show us the lint and style errors before we push to GH. 

I have mixed feelings about having flake8 display warnings vs error out but i suspect once we get the code stable we won't have much to do there.

So i'm in support of adding black and isort to the build-lint.yml file and maybe renaming it style-lint.yml or something like that given black is i think considered a styler.

**Comment by lwasser** [comment]
hey @yihong0618 i believe we did address this issue with pre-commit hooks and such. i am going to close this issue however please reopen it if you think there is more work to do on our linting / code formatting workflows!! :)
