### ISSUE TITLE
How should we manage the changelog? What do we want our release workflow to look like?

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#260]
Hi everyone - this relates to a[ comment here](https://github.com/stravalib/stravalib/pull/259/files#r1026112641) in the open pr that adds a CI build for releasing to PyPI. Essentially we need to decide how we want to manage releases and changelog.

Previously the changelog was in the docs folder but i think it's better to have it in the main repository root dir. I also turned it into a .md file and will update docs to support markdown accordingly so it can be in the docs. 
*****
In previous package workflows i've used a changelog process where on each PR we make sure the changelog is updated. 
The changelog will then tell us 

* what changes were made, who made them and what ISSUE they addressed. In this workflow the issue was then tied to a PR and closed upon pr merge.  

## Other options for change log 

I've also seen changelogs that just link to the PR rather than the issue. the only downside is sometimes the pr doesn't have the backstory of why those changes were made. 

Finally some people just use the GITHUB changelog when they create a release ... which will add pr's since the last release, who contributed etc which could also be ok. this just depends upon people using clear commit messages when we merge.  The downside of only using the github created changelog is that we wouldn't have the changelog in the docs. which i think could be ok too. 

@jsamoocha @hozn @yihong0618 any preferences here?

I am going to submit a new PR when my current one is merged with all of this documented btw.

**Comment by hozn** [comment]
No preference from me.  At past couple jobs we've (often) adopted the basic ideas in https://keepachangelog.com/en/1.0.0/ -- but that doesn't really address many of your questions, just more of a structure.  I agree with the Changelog being top-level; that's where folks look for it.  (And markdown is great!)

**Comment by jsamoocha** [comment]
Let's make it a habit to always update the changelog upon creating/merging a PR (or ask the PR author to do so). I also think the subheadings @hozn referred to above (Added, Changed, Deprecated, Removed, Fixed, Security) would be good to add to every release.

The format you chose for the latest additions to the existing changelog are fine for me.

About release workflow: let's try to not overcomplicate things and allow maximum speed/flexibility in case of sudden breaking changes at the Strava side of things (which happened a few times in the past).

**Comment by lwasser** [comment]
Ok i'm all for updating the changelog on every pr. in fact i'll just create a defactor pr template that asks you if you've done that as a reminder.

So looking at that [keepachangelog](https://keepachangelog.com/en/1.0.0/) link above.

## Guiding Principles
Changelogs are for humans, not machines.
There should be an entry for every single version.
The same types of changes should be grouped.
Versions and sections should be linkable.
The latest version comes first.
The release date of each version is displayed.
Mention whether you follow [Semantic Versioning](https://semver.org/).

## Types of changes
**Added** for new features.
**Changed** for changes in existing functionality.
**Deprecated** for soon-to-be removed features.
**Removed** for now removed features.
**Fixed** for any bug fixes.
**Security** in case of vulnerabilities.

## This brings up one more question

Do we want to follow [semantic versioning](https://semver.org/)
If we do we'd adhere to this for version updates:
```
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes
MINOR version when you add functionality in a backwards compatible manner
PATCH version when you make backwards compatible bug fixes
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```

In this case i think we are moving towards a major release if we follow semver as we're dropping python 2.x. 

so we'd be moving to version 1.0 upon next release (i think).
feedback please! i'll document this all once we decide.

**Comment by jsamoocha** [comment]
1.0 for the next release seems justified because of dropping python 2.

**Comment by lwasser** [comment]
ok great. And then I think this is our workflow for merging pr's. 

* if the PR is a change or addition let's make sure we have (2) maintainer approvals?
* If the PR is a small fix that the maintainer is confident in and all tests run with the fix then they can merge without a review? this makes me a bit nervous BUT let's try it !!

## release workflow

For a release we probably want a process that involves a PR with the changelog cleanup and a maintainer approval?
 i am going to propose a workflow for that in that PR i keep mentioning that documents all of this :) 

Lets go with a 1.0 release. what pr's should be included in that? Should we just merge the two that are approved and then do a release tonight? i want to do this release just to test my build and fix it in case i did make a mistake on the real pypi end of things if that works for you.

**Comment by jsamoocha** [comment]
> Lets go with a 1.0 release. what pr's should be included in that? Should we just merge the two that are approved and then do a release tonight?

If you mean #227 and #240, yes, let's merge these as well.

**Comment by lwasser** [comment]
have you tested #227 or #240 @jsamoocha ?? i'll try to get pypi working here in the next few hours!! hoping it's small as it was working on my branch

**Comment by lwasser** [comment]
ok i've tested merged and cleaned up those two pr's. I am going to close this and open a new issue for our first RELEASE 1.0 in a really long time!!
