### ISSUE TITLE
I believe the rate-limiter doesn't work in stravalib

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#288]
I'm not adding too much detail here but i've tried to use it and it didn't seem to work. Also a colleague tried as well. So either it's broken or it needs better documentation :) i'll play iwth this more to try to create a reproducible example once we are done with all of these bigger infrastructure updates!

**Comment by tnikkel** [comment]
I've found the same thing. My solution was to just comment out the "self.rules.append(XRateLimitRule..." in limiter.py and uncomment the first RateLimitRule line below.

**Comment by jsamoocha** [comment]
Have you tried `SleepingRateLimitRule` (as an alternative to `XRateLimitRule`)? I am using it without apparent issues. We may need to add some integration tests and documentation about how to "plug in" other rate limiters than the default `XRateLimitRule`. An example could be (copied from how I use it):

```python
from stravalib.util.limiter import RateLimiter, SleepingRateLimitRule
from stravalib import Client

class SleepingRateLimiter(RateLimiter):
    def __init__(self, priority='medium'):
        super().__init__()
        self.rules.append(SleepingRateLimitRule(priority=priority))

client = Client(access_token='XYZ', rate_limiter=SleepingRateLimiter(priority))
```

**Comment by lwasser** [comment]
hey there @tnikkel 👋  thanks for verifying this!!  

looks like there may be an alternative approach.  and at a minimum we need some good documentation around this or just a code update to make it easier to apply the limiter?

**Comment by jsamoocha** [comment]
Maybe related to #154 ?

**Comment by lwasser** [comment]
hey @jsamoocha i'm reading back through this and somehow i missed your comments twice. i'm so sorry!

Given you recently updated the rate limiter and it worked great, i think we can close this issue and #154 that you referenced above!  i'm just trying to clean up old issues since i'm online now :) i'll go ahead and close both. If you or anyone thinks we need to reopen we can. but i feel like they are fully resolved now.
