### ISSUE TITLE
Create guidelines for what version of python we support

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#301]
I've been chatting with colleagues and a standard for python spuport is the[ NEP-29 protocol](https://numpy.org/neps/nep-0029-deprecation_policy.html)

I suggest that we follow that policy in terms of dropping older versions of python to adhere to the broader community's approach. This actually is perfectly inilne with the drop that we just made for python 3.7. 

What do you all think about implementing this as a development / release policy?
[Python end of life map here:](https://endoflife.date/python).

essentially we'd then support python versions released in the past 3.5 years (42 months) to align with a broader community of packages.

**Comment by enadeau** [comment]
I think it's a good idea to adhere to this broader standard. The fact that pint also follows this is also pushing me in that direction. Seems like a good compromise between being able to use modern feature and support many versions of python

**Comment by lwasser** [comment]
i agree. i am happy to add this to the dev guide documentation. i think i opened this when i was initially thinking about dev and writing our dev guide. 

we can be a bit less aggressive too if we wish about dropping versions but 3.8 is fairly dated at this point. so i'd feel ok with us dropping it now especially given the issues you're running into !

**Comment by enadeau** [comment]
Nice let's move forward with this I can take care of the PR that removes support for 3.8

**Comment by lwasser** [comment]
i created a quick query to look at downloads. [the tool i used ](https://github.com/ofek/pypinfo/issues)didn't specify the timeframe for a stock query but i'm guessing a month based on our typical weekly downloads. most of our users are on 3.9 so i feel good about this drop. perhaps it will encourage folks to upgrade as well as 3.11 is the current recommended version!

i'll be able to look more closely at your pr, @enadeau soon! i just wanted to share this as i was curious. 

| python_version | download_count |
| -------------- | -------------- |
| 3.9            |         15,152 |
| 3.8            |          2,924 |
| 3.10           |          1,676 |
| 3.11           |          1,604 |
| 3.7            |          1,131 |
| 2.7            |             40 |
| 3.6            |             10 |
| 3.12           |              3 |
| Total          |         22,540 |

**Comment by lwasser** [comment]
i think that we can close this issue now. If I am missing something please let me know! i think we should just follow the general lifecycle of supported versions of python!
