### ISSUE TITLE
/activities/{id} not working

### ISSUE THREAD

**Issue by gitexel** [stravalib/stravalib#305]
When I try to get activity, it always returns this error:
`stravalib.exc.ObjectNotFound: Not Found: Resource Not Found: [{'resource': 'Activity', 'field': '', 'code': 'not found'}]
`

access token scope: `activity: write;read_all;`
stravalib version : 1.1.0
endpoint: `/activities/{id}`

**Comment by jsamoocha** [comment]
Hi, according to [the API doc](https://developers.strava.com/docs/reference/#api-Activities-getActivityById) you need an `activity:read` or `activity:read_all` scope on your access token. Can you try an access token with one of these scopes?

**Comment by gitexel** [comment]
Thanks @jsamoocha , I was combining scopes wrongly 😅 .
This is the correct approach `scope=activity:read_all,activity:write`. works for me 😄

**Comment by lwasser** [comment]
Just in case anyone is also stuck on this adding a bit of detail:

If you are using the `client()` object, your scope variable should look like this for proper write permissions. 

`scope=["read_all", "profile:read_all", "activity:write", "activity:read_all"]`

this will allow you both read and write permissions when you get the auth code!
i'm going to update our authentication tutorials with more specifics about this as it's not clear there! many thanks for this issue @gitexel !

**Comment by lwasser** [comment]
hey @gitexel just curious - were you able to get the data to actually upload to a profile?
The client object seemed to accept the scope but i don't actually see the activity in strava. so i'm curious. i'm using a .fit file from training peaks but it's also an activity already on strava. curious what you are seeing!

i don't know if 
1. i'm doing something wrong or 
2. it's failing quietly ?
```
f = "tp-1826853.2023-01-05-15-20-11-426Z.GarminPing.AAAAAGO26qqbGy_d.FIT"
# This creates an uploader object but does it actually upload?
c = client.upload_activity(f, data_type="fit", 
                        name="LALALA", 
                        activity_type="run")
```

response object:

```
>>> c.is_processing
True
>>> c.is_complete
False
```

**Comment by gitexel** [comment]
Hi @lwasser, yes after I changed the scope to `activity:read_all` and `activity:write`  I was able by calling `c.wait()` will check the upload status and then return `activity` object if `activity_file` is successfully uploaded and processed and will raise an error if something went wrong.

Thank you @lwasser for your help :)
