### ISSUE TITLE
Add MANIFST.in to our package to trim down SDist 

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#307]
Our current SDist package has ALL of the documentation files and such included . 🙈 
it's ugly!
 
If we had an MANIFEST.in file with excludes it will be a cleaner (and smaller) distribution. 
I will work on this after the linting items have been merged. it's a small fix. 

[more here](https://packaging.python.org/en/latest/guides/using-manifest-in/)

**Comment by lwasser** [comment]
OR just move the build to hatchling + hatch (or pdm?)

**Comment by ofek** [comment]
Hatch/Hatchling maintainer here, let me know if you have any questions!

**Comment by lwasser** [comment]
hi there @ofek :wave:

Thank you so so much! i do think it's time for us to migrate!! :)  and i'll ping ya with questions if i break things. 

 The only thing that I have (minor0 questions around now is whether we need to think about dependency management (the only reason why i considered PDM)! We don't have any dependency management now aside from adding deps to the pyproject.toml and requirements file manually without version pinning. but i was thinking about swapping out:

*  setuptools_scm with hatch_vcs 
*  setuptools  / build with hatch / hatchling

first. and i heard that you *might* be considering some sort of dep management in the future maybe? (word of mouth 🙈 so i could be wrong!)

Pradyun guided me through moving away fully from setup.py and setup.cfg so we are on our way to being fully modern! 🎉 

BTW i LOVE the Hatch logo and docs!

**Comment by lwasser** [comment]
@jsamoocha when you have a few - look here: [hatch](https://hatch.pypa.io/latest/) is really nice, extensible and flexible and MODERN. i don't think the change would be huge we can still pick our environment manager as we wish to locally. we also *might* be able to get rid of some of the make files i think  in a second update (i won't do that right away).
