### ISSUE TITLE
META: check client methods vs. Strava API consistency

### ISSUE THREAD

**Issue by jsamoocha** [stravalib/stravalib#323]
Methods from the `client` module can have one of the following states compared with the Strava API:

1. Officially documented
2. Officially deprecated
3. Undocumented but somehow working
4. Undocumented and unsupported (returning 4XX responses)

We need to systematically check the methods in `client`, and for states 2/3/4, we need to investigate possible solutions and create new issues where necessary.

**Comment by futureshape** [comment]
Issue #238 has an example of a method removed from the Strava API but still in the library

**Comment by lwasser** [comment]
@jsamoocha is there anything left todo on this task? i think the[ one issue](https://github.com/stravalib/stravalib/issues/528) around checking undocumented attributes is a good one for us to implement! But i think we've gone through most if not all of the API endpoints at this point to check for what's documented and what's returned. 

Can we close this? ✨

**Comment by jsamoocha** [comment]
Given our limited availability, it may be better to deal with inconsistencies between Strava API and our client methods on a case-by-case basis (i.e., when a user reports something is broken or doesn't work as expected), instead of the proactive approach suggested in this issue. Closing this now.
