### ISSUE TITLE
Potential issue with backwards compatibility of returned objects

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#330]
@jsamoocha 
I just delete the version things then test.

there is a break change in my repo.

check 
https://github.com/yihong0618/running_page/blob/master/scripts/generator/__init__.py#L55

old return str like "Run"

now return a model --> ActivityType.Run

![image](https://user-images.githubusercontent.com/15976103/216861003-6dbad8b0-d69b-476b-839f-d1f5f73236da.png)

_Originally posted by @yihong0618 in https://github.com/stravalib/stravalib/issues/328#issuecomment-1418358205_

**Comment by yihong0618** [comment]
for version things
we can not find `_version_generated` if use pip install

**Comment by lwasser** [comment]
@yihong0618 i think pr #329  is actually what @jsamoocha 

can you please have a look at that pr and see if it fixes your issue? i just tested it and now the return is a string rather than the ActivityType object. if this fixes your issue we can close this issue - i just approved that pr!

**Comment by jsamoocha** [comment]
Closed by #350
