### ISSUE TITLE
Issue with installing stravalib remotely

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#331]
version python3.10

 pip3 install git+https://github.com/stravalib/stravalib.git@pydantic_model

one issue raise error
```python 
import stravalib 

```
![image](https://user-images.githubusercontent.com/15976103/216820672-a84b722f-87d9-47b9-baa5-82c9b9a3115b.png)

_Originally posted by @yihong0618 in https://github.com/stravalib/stravalib/issues/328#issuecomment-1417804578_

**Comment by lwasser** [comment]
from @jsamoocha 
> No problems at my end:
> 
> ```
> ❯ python
> Python 3.10.9 (main, Jan  2 2023, 14:22:15) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import stravalib
> >>>
> ```
> 
> I installed using pipenv:
> 
> ```
> pipenv install -e git+https://github.com/jsamoocha/stravalib.git@fix_enums#egg=stravalib
> ```
> 
> or
> 
> ```
> pipenv install -e git+https://github.com/stravalib/stravalib.git@pydantic_model#egg=stravalib
> ```
> 
> What happens when you install using the `-e` flag?

**Comment by lwasser** [comment]
This worked for me - 

```bash
# Create fresh envt
➜ conda create -n py310 python=3.10
➜ pip install -e git+https://github.com/stravalib/stravalib.git@pydantic_model#egg=stravalib
```

Important - the default install will always come from the package flat files first. so you'd want to call python from a different directory - one that is a directory or two ABOVE stravalib. this will ensure that you are calling stravalib from the envt rather than the flat files (but of course it's also still odd that you're getting that error from the flat files if that is the case)

```python
>>> import os
>>> os.getcwd()
../stravalib
>>> os.chdir("change-to-another-dir-not-in-stravalib")
>>> import stravalib
```

if this doesn't work maybe we can look at the homebrew install of python next? i am using a conda install. not sure what jonatan is using?

@yihong0618 what envt manager are you using? maybe i can try again to recreate what you are seeing with another envt manager?

**Comment by yihong0618** [comment]
still not work.
and I think its not a better idea that a version file can break all things .

**Comment by jsamoocha** [comment]
> and I think its not a better idea that a version file can break all things .

Agree with this. Whenever we install stravalib from PyPI, the version file will be included because of the build/release workflow. In case of any type of "alternative" install (like above), there should be some sensible default (something like "test" or "unreleased"?). Successful installation/testing of a branch should not depend on particular pip settings or virtualenv management.

**Comment by jsamoocha** [comment]
I'm not sure if it will work (@lwasser , you added and tested this construction in the past if I'm not mistaken?), but will it fix this issue when `_version.py` looks like the snippet below?

```python
"""
Get the automatically generated version information from setuptools_scm
Format it: vX.Y.Z
"""

try:
    # This file is generated automatically by setuptools_scm
    from . import _version_generated
    
    # Add a "v" to the version number made by setuptools_scm
    __version__ = f"v{_version_generated.version}"
except ImportError:
    # Maybe log a warning??
    __version__ = 'Unreleased'
```

**Comment by yihong0618** [comment]
agree with above.

**Comment by yihong0618** [comment]
or we can just add version file manually ?

**Comment by lwasser** [comment]
I agree. I did a bit of digging last night into other packages that use
this scm.

We can use a try/accept in init.py and omit the version.py file altogether.
We then create the version attribute there.

Doing this will remove an additional import and the try accept will allow
install in dev mode.

Let me test and I'll submit a pr in the next few days if it works as
expected

**Comment by lwasser** [comment]
@yihong0618 @jsamoocha can you please try this:

`pip install git+https://github.com/lwasser/stravalib.git@fix-scm`

then 

```python
>>> import stravalib
>>> stravalib.__version__ 
# what version do you see if any? If the above works...
```

**Comment by jsamoocha** [comment]
```
Python 3.10.9 (main, Jan  2 2023, 14:22:15) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import stravalib
>>> stravalib.__version__
'v0.10.4.post118'
>>>
```

🎉: it doesn't crash
🤔: where does v0.10.4 come from??

**Comment by lwasser** [comment]
can you please run 

`git tag` 

have you updated tags in a while? i just wonder if your list of tags is not up to date

**Comment by lwasser** [comment]
scm grabs the version from the most recent tag. this is why making a tagged release on github works. if for some reason your local tags are not up to date it will grab the most recent one.  actually this is may be on my repo's end not yours... let me check.

**Comment by lwasser** [comment]
it was - i hadn't updated tags on my repo so the most recent was 10.4 - i just pushed the updated tags and now 1.1 is there - https://github.com/lwasser/stravalib/tags

**Comment by lwasser** [comment]
> Ok, looking really good now, I see `'v1.1.0.post25'`!

oh yay! 🎉 

 @yihong0618 please test as well when you have time. 

I'll submit a PR if it works for you too. i think this actually is a better way to implement things vs. the way we were doing it before. as it should never fail - addressing the original point that a version file should never break an entire install / build. i just had never had someone install from github remotely that way to see the error.

**Comment by lwasser** [comment]
Excellent. Looking at your output I'll change the except output to say
"unreleased" rather than unknown
