### ISSUE TITLE
New release - please test - AttributeError: module 'collections' has no attribute 'MutableMapping' upon import stravalib (conda envt)

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#339]
hey there y'all...
i've been messing with various environments and am trying to figure out if this is a stravalib issue or a "i broke my environment issue". can someone please test installing from testpypi and seeing if you can import stravalib?

`$ pip install -i https://test.pypi.org/simple/ stravalib`

```python
>>> import stravalib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/leahawasser/mambaforge/envs/test-stravalib/lib/python3.10/site-packages/stravalib/__init__.py", line 1, in <module>
    from stravalib.client import Client
  File "/Users/leahawasser/mambaforge/envs/test-stravalib/lib/python3.10/site-packages/stravalib/client.py", line 19, in <module>
    from stravalib import exc, model, unithelper
  File "/Users/leahawasser/mambaforge/envs/test-stravalib/lib/python3.10/site-packages/stravalib/exc.py", line 10, in <module>
    import requests.exceptions
  File "/Users/leahawasser/mambaforge/envs/test-stravalib/lib/python3.10/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/Users/leahawasser/mambaforge/envs/test-stravalib/lib/python3.10/site-packages/requests/utils.py", line 30, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/Users/leahawasser/mambaforge/envs/test-stravalib/lib/python3.10/site-packages/requests/cookies.py", line 159, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

[i did find this SO post](https://stackoverflow.com/questions/70970307/python-error-class-requestscookiejarcookielib-cookiejar-collections-mutablema) BUT again i want to understand if this is my envt specifically or something we need to fix in stravalib. i'm using a clean, newly installed python via mambaforge with a fresh new envt with nothing but the basic libraries. BUT because i'm using conda there is some serious channel mixing that happened when i installed stravalib (which can be fixed when i add it to conda-forge) BUT i don't want to do that until we merge in that pydantic branch.

```
arrow                     0.7.0                    pypi_0    pypi
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2022.12.7            h4653dfc_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libsqlite                 3.40.0               h76d750c_0    conda-forge
libzlib                   1.2.13               h03a7124_4    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
openssl                   3.0.8                h03a7124_0    conda-forge
packaging                 16.7                     pypi_0    pypi
pint                      0.18                     pypi_0    pypi
pip                       23.0               pyhd8ed1ab_0    conda-forge
pydantic                  1.5a1                    pypi_0    pypi
pyparsing                 2.4.6                    pypi_0    pypi
python                    3.10.9          h3ba56d0_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2018.5                   pypi_0    pypi
readline                  8.1.2                h46ed386_0    conda-forge
requests                  2.5.4.1                  pypi_0    pypi
setuptools                67.3.2             pyhd8ed1ab_0    conda-forge
six                       1.10.0                   pypi_0    pypi
stravalib                 1.1.0.post30             pypi_0    pypi
tk                        8.6.12               he1e0b03_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
```

btw this did used to work - installing stravalib into a conda envt

## Conda info 

     active environment : test-stravalib
    active env location : /Users/leahawasser/mambaforge/envs/test-stravalib
            shell level : 2
       user config file : /Users/leahawasser/.condarc
 populated config files : /Users/leahawasser/mambaforge/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=arm64
                          __osx=12.6.2=0
                          __unix=0=0
       base environment : /Users/leahawasser/mambaforge  (writable)
      conda av data dir : /Users/leahawasser/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/leahawasser/mambaforge/pkgs
                          /Users/leahawasser/.conda/pkgs
       envs directories : /Users/leahawasser/mambaforge/envs
                          /Users/leahawasser/.conda/envs
               platform : osx-arm64
             user-agent : conda/22.11.1 requests/2.28.2 CPython/3.10.9 Darwin/21.6.0 OSX/12.6.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False

## After installing upling
And after `pip install uplink`, this is my envt:

```
# packages in environment at /Users/leahawasser/mambaforge/envs/test-stravalib:
#
# Name                    Version                   Build  Channel
arrow                     0.7.0                    pypi_0    pypi
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2022.12.7            h4653dfc_0    conda-forge
certifi                   2022.12.7                pypi_0    pypi
charset-normalizer        3.0.1                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
libffi                    3.4.2                h3422bc3_5    conda-forge
libsqlite                 3.40.0               h76d750c_0    conda-forge
libzlib                   1.2.13               h03a7124_4    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
openssl                   3.0.8                h03a7124_0    conda-forge
packaging                 16.7                     pypi_0    pypi
pint                      0.18                     pypi_0    pypi
pip                       23.0               pyhd8ed1ab_0    conda-forge
pydantic                  1.5a1                    pypi_0    pypi
pyparsing                 2.4.6                    pypi_0    pypi
python                    3.10.9          h3ba56d0_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2018.5                   pypi_0    pypi
readline                  8.1.2                h46ed386_0    conda-forge
requests                  2.28.2                   pypi_0    pypi
setuptools                67.3.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
stravalib                 1.1.0.post30             pypi_0    pypi
tk                        8.6.12               he1e0b03_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
uplink                    0.9.7                    pypi_0    pypi
uritemplate               4.1.1                    pypi_0    pypi
urllib3                   1.26.14                  pypi_0    pypi
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
```

**Comment by lwasser** [comment]
`pip install uplink` DOES fix this. but i don't understand why (except that uplink doesn't seem to live on conda?). but why is this happening now when it didn't happen previously?

**Comment by jsamoocha** [comment]
I can install and import from that test release, and tested it with python 3.8 and 3.10.

My env looks as follows:

```
❯ pipenv graph
stravalib==1.1.0.post30
  - arrow [required: Any, installed: 1.2.3]
    - python-dateutil [required: >=2.7.0, installed: 2.8.2]
      - six [required: >=1.5, installed: 1.16.0]
  - pint [required: Any, installed: 0.20.1]
  - pydantic [required: Any, installed: 1.10.5]
    - typing-extensions [required: >=4.2.0, installed: 4.5.0]
  - pytz [required: Any, installed: 2022.7.1]
  - requests [required: Any, installed: 2.28.2]
    - certifi [required: >=2017.4.17, installed: 2022.12.7]
    - charset-normalizer [required: >=2,<4, installed: 3.0.1]
    - idna [required: >=2.5,<4, installed: 3.4]
    - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.14]
```

What is your python version for that conda env?

The version of `requests` you listed above seems (very) old: on Github, and in my environment, the most recent version is 2.28.2. The same goes for several other dependencies listed in your environment.

From python 3.10, `collections.MutableMapping` doesn't exist anymore and needs to be imported from `collections.abc` (see e.g. https://stackoverflow.com/questions/70870041/cannot-import-name-mutablemapping-from-collections). If you're using py 3.10, that explains why you see that `AttributeError`.

I'm not a conda expert and have no idea why conda is installing these old versions of dependencies in your case.

**Comment by lwasser** [comment]
interesting. i'm using python 3.10.9 in this environment . i added some envt info to the above. essentially when i pip installed uplink it updated requests. i still don't understand why.  maybe i'll push this package to conda-forge sooner than later as well. it seems like it might be something in how pip is resolving dependencies in a conda envt? 🤷‍♀️ i'm not sure how much of our user base uses conda but i do.

**Comment by lwasser** [comment]
ok i have collected some more information..
The suspicion is that when i installed from testpypi, it used test pypi to resolve dependencies. There must be something about pipenv that uses both test and the regular pypi! 
https://test.pypi.org/project/requests/ 

i dont think this is an issue with our package - just the tools that we are all using and how the resolve (and from where). I'll go ahead and create a release now! and will test again - i suspect it will be fine. i'll then bump up the push to conda forge just in case we have other conda users out there! i'll close this for now but feel free to reopen if there are any concerns!

**Comment by lwasser** [comment]
ok stravalib 1.2.0 is released!! 🥳 it seems to install just fine - i think test pypi causes it's own problems so that is good for me to know for future testing!! if everyone did what we did test pypi packages would be current but not everyone uses it.

**Comment by jsamoocha** [comment]
Supposedly (based on which env manager one uses), dependencies are resolved against test pypi when installing from there. Since that arbitrary package "uplink" was not listed on test pypi, its dependencies were resolved against the real pypi.  "Interesting" 🤪
