### ISSUE TITLE
Black isn't running on pr's and was turned off in our pre-commit file

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#357]
in #356 i realized that black was not actually running on our pr's. i've turned it back on but if we run it on that pr it will be a big change to all files. i had thought we already did this but i must be remembering incorrectly. 

Should we run pre-comit autofix on the current pr once we are happy with docstrings ? 
This would allow for the entire code base to have proper formatting  (isort and black). 

we could then merge and I can then continue to work on docstring and code cleanup submitting a few files at a time for easy review.

**Comment by jsamoocha** [comment]
Let's enable this, as there is no big feature branch anymore for which this would create merge conflicts.

**Comment by lwasser** [comment]
just a note - i also am exploring whether we can force the pre-commit ci bot to ONLY modify / check files in the pr. 

if we can not get this to work we could consider using - https://pypi.org/project/darker/ instead! as i seems to run black but in a more targeted way.

**Comment by lwasser** [comment]
ok i've enabled this so we can close this issue. it looks like we can't fix black running on ALL files in pr's given the way it's setup without setting up a specific ci build. But i suspect now that we have everything linted, it will be ok in the future as if someone only fixes a few files, only those have potential linting issues. closing this!
