### ISSUE TITLE
Remove legacy model deserialize() calls from client

### ISSUE THREAD

**Issue by jsamoocha** [stravalib/stravalib#358]
We need some cleanup that removes deprecated `deserialize()` calls on model classes and replaces these with pydantic's `parse_obj()`.

**Comment by lwasser** [comment]
NOTE:  from_dict also has a deprecation in favor of parse_obj but there is some [hackiness there](https://github.com/stravalib/stravalib/blob/main/src/stravalib/model.py#L232) (see last line of the method)
