### ISSUE TITLE
release 1.3?

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#361]
Right now we have a [release candidate ](https://pypi.org/project/stravalib/#history) on stravalib which means when people pip install they get version 1.2. given this has been out for 2 months, should we just bump to 1.3 now? 

install for the current release candidate is `pip install stravalib==1.3.0rc0`

**Comment by lwasser** [comment]
I just made a release. i combined the features from the rc0 with the full release as technically this will now contain both for anyone pip installing this package. i'm going to look a bit more to see how others handle rc vs full releases in terms of change logs and docs as well. :)

**Comment by jsamoocha** [comment]
Thanks @lwasser! I'm not sure the release made it entirely: this repo says 1.2 is the latest release, and so does the documentation online. When I install stravalib, the version mentioned is also 1.2.0.post22. The funny thing is that pypi says the latest release is 1.3.0 (released yesterday). I checked the pypi push action log, and 1.3.0 was not in the fetched tags. Do you have any idea what's going on?

**Comment by lwasser** [comment]
Oh gosh. Thank you for noticing that! I am at pycon let me dig into that
today. I saw 1.3 on pypi and thought all was good. I will try to see what's
going on today as I'm running a sprint and will be around lots of python
people

>
.Message ID: ***@***.***>
>
