### ISSUE TITLE
Validation Errors for activities with segments and activity type AlpineSkiing

### ISSUE THREAD

**Issue by solorisx** [stravalib/stravalib#368]
When trying to get an activity with `client.get_activity({id})`, I get validation errors when the activity has segments and the activity type is AlpineSkiing. I don't have another activity type to test, but I suspect this applies to any activity type other than  Run or Ride.

`Traceback (most recent call last):
  File "xxxxx/test.py", line 44, in <module>
    activity = client.get_activity(activity_id=xxxxx)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxxxx/.local/lib/python3.11/site-packages/stravalib/client.py", line 574, in get_activity
    return model.Activity.parse_obj({**raw, **{"bound_client": self}})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 38 validation errors for Activity
segment_efforts -> 0 -> segment -> activity_type
  unexpected value; permitted: 'Ride', 'Run' (type=value_error.const; given=AlpineSki; permitted=('Ride', 'Run'))
segment_efforts -> 1 -> segment -> activity_type
  unexpected value; permitted: 'Ride', 'Run' (type=value_error.const; given=AlpineSki; permitted=('Ride', 'Run'))
segment_efforts -> 2 -> segment -> activity_type`

I believe this stems from the following line in strava_model.py:
`class SummarySegment(BaseModel):
    activity_type: Optional[Literal["Ride", "Run"]] = None`

If it's ok with you, I would fix that and extend it to other activity types and test it. I would suggest using the class `ActivityType` for validation even though technically only GPS-based activities can have segments.

**Comment by jsamoocha** [comment]
Hi, thanks for reporting this!

The inconsistency in the typing seems to be a problem with the Strava API itself; see https://developers.strava.com/docs/reference/#api-models-SummarySegment. Bugs and remarks about the Strava API can be reported [here](https://communityhub.strava.com/t5/developer-discussions/bd-p/developer-discussions).

Meanwhile, we could work around the issue by loosening the type to, e.g., `str` in the `Segment` class in `model.py` (see the `#field overrides ...` section). Be aware that `strava_model.py` cannot be edited as it is generated from the API itself. It would be awesome if you could give it a try!

**Comment by solorisx** [comment]
Thanks, I reported the inconstency in the strava forum and made a pull request for a workaround.
