### ISSUE TITLE
SummarySegment missing activity types

### ISSUE THREAD

**Issue by inspiran** [stravalib/stravalib#370]
Hi,

On this activity https://www.strava.com/activities/6642142720 I am getting following error:

<class 'pydantic.error_wrappers.ValidationError'>6 validation errors for Activity
segment_efforts -> 0 -> segment -> activity_type
  unexpected value; permitted: 'Ride', 'Run' (type=value_error.const; given=VirtualRide; permitted=('Ride', 'Run'))

Most likely this is due to class SummarySegment(BaseModel) having the following restricted list of attributes.
`    activity_type: Optional[Literal["Ride", "Run"]] = None`

Perhaps it should be:
` class SummarySegment(BaseModel):
    activity_type: Optional[Literal["Ride", "Run", "VirtualRide", "VirtualRun"]] = None`

**Comment by jsamoocha** [comment]
Hi, I think this was fixed a few weeks ago; see #368. Please check that issue (and resolution), and if you think it solves the above, feel free to close this issue. If you think I'm missing something, please continue the conversation!

**Comment by inspiran** [comment]
Oh thank you, i was indeed using 1.3 but not the master version.  When would this be tagged in a new release?

**Comment by jsamoocha** [comment]
I just released v1.3.1, which includes the fix; hopefully, that'll resolve your problem 🙂

**Comment by jsamoocha** [comment]
Closing this issue, assuming the previous release resolved it.

**Comment by inspiran** [comment]
Sorry about the late reply, i've put it last week into production and it seems to work perfectly splendid.

(it's [www.trainingsparkle.com](url) , a service to allow you create a digital book out of your Strava/Garmin activities)
