### ISSUE TITLE
New pydantic release -- parse_datetime has been removed & is causing errors in our test runs.

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#379]
Pydantic has JUST release 2.0 and our builds are not failing due to this:

[tests are also failing ](https://github.com/stravalib/stravalib/actions/runs/5425675105/jobs/9866739005#step:11:24)

`pydantic.errors.PydanticImportError: `pydantic.datetime_parse:parse_datetime` has been removed in V2.`

locally tests run on my machine but i'm still running pydantic 1.10.9. i just pushed a pinned version of pydantic to ensure this is indeed the issue.

**Comment by jsamoocha** [comment]
Ok, great! I'm super busy and don't have time to address the exact issue in the short term. I'll cherry-pick the pydantic pin from your changes and make a new PR + release based on that to prevent new stravalib installs from failing.

**Comment by jsamoocha** [comment]
Oops, we also needed to update the dependencies in pyproject.toml. New release coming...

**Comment by jsamoocha** [comment]
Ok, v1.3.3 works. I hope you don't mind I took some shortcuts regarding our release process to prevent users from having install issues. And sorry for the release spam 🙈

**Comment by lwasser** [comment]
😆 no worries - i should have been more clear that i was just testing by pinning my environment. glad you caught the .toml file wasn't updated!! 

it seems like we need to
1.  remove that from `parse_datetime` method . it's only in one module. so we can get to it when there is time. 

so [here](https://github.com/stravalib/stravalib/blob/master/stravalib/model.py#L126) and [here](https://github.com/stravalib/stravalib/blob/master/stravalib/model.py#L126)

2. [modify the code a bit to handle inputs in expected formats](https://github.com/pydantic/pydantic/discussions/6204) . Will we ever have an input that isn't a string pulled from the JSON here?

**Comment by lwasser** [comment]
so following up on this (please tell me if i'm mis understanding how this works

strava's API will return a datetime that looks something like this in a JSON format that will be deserialized to a dict so it should be a string value : 
`value = "2018-02-20T18:02:13Z"`


the function that is an issue looks like this

**Comment by jsamoocha** [comment]
It's a bit tricky, because we need to parse in two directions:

1. JSON coming from Strava,
2. Any `datetime`, `str`, `int`, etc. that can be parsed into a `datetime`, coming from the user.

I see that this parsing behavior is not fully tested either on our end. Worst-case we can opportunistically copy/paste the code from Pydantic v1.

**Comment by lwasser** [comment]
ok this makes sense. i tried to just use datetime and of course it did break things. Looking at pydantic's parsedatetime module - [it's fairly complex](https://github.com/pydantic/pydantic/blob/0e8a387d6752dd859676da53298601ccae6a23a7/pydantic/datetime_parse.py) they are using regex as apparently that is what django does 😵‍💫 but it allows for more flexibility and user-friend interface (according to their notes).

Should i attempt to port that over as a utility module and port tests and link back to pydantic authors in the notes? it's a good bit of code. i'm also digging around to see if there is another package that does something similar. it seems like that would be preferred rather than us picking up another ~200 lines of code to maintain. 

im guessing that if i work on this the timeline will be slower than the time it would take for you to do it but i'm open to taking a stab at it / adding tests etc and am open to feedback.

**Comment by lwasser** [comment]
it seems like the alternative to try would be what was [suggested here. ](https://github.com/pydantic/pydantic/discussions/6204#discussioncomment-6266717)

```
from pydantic import TypeAdapter

from datetime import datetime
parse_datetime = TypeAdapter(datetime).validate_json
```

> If you wanted to accept either JSON or Python objects like the original parse_datetime you might need to wrap that in a function that does isinstance(obj, datetime) or something.

And then we'd have some specific conditionals to check for other potential input types. i'm unclear of how many different input types we'd want to support here however. 

* datetime (easy), string (this could be anything right?), int (seconds?). 

then we could write tests for each potential input type. i actually don't see any tests that directly call `naive_datetime` so that should be added here as well. could we first determine the suite of input types that we expect? i can then work on this. i'd probably do it test based - write the tests first then (re)build the function.

**Comment by jsamoocha** [comment]
Here's the implementation from the pre-pydantic version 1.2.0 of stravalib (as reference for what was supported initially):

```
    def unmarshal(self, v):
        """
        Convert a timestamp in "2012-12-13T03:43:19Z" format to a `datetime.datetime` object.
        """
        if not isinstance(v, datetime):
            if isinstance(v, int):
                v = arrow.get(v)
            else:
                try:
                    # Most dates are in this format 2012-12-13T03:43:19Z
                    v = datetime.strptime(v, "%Y-%m-%dT%H:%M:%SZ")
                except ValueError:
                    # ... but not all.
                    v = arrow.get(v).datetime
            # Translate to specified TZ
            v = v.replace(tzinfo=self.tzinfo)

        return v
```

**Comment by jsamoocha** [comment]
The Pydantic V2 [migration guide](https://docs.pydantic.dev/latest/migration/) is quite intimidating. I glanced over it; there are many more potential issues and deprecations. I'm afraid that switching to Pydantic V2 will require some effort.

Maybe we should focus first on the current typing exercise, documentation upgrade, and test coverage before upgrading Pydantic? At least, I'd feel more comfortable doing so when we have near 100% coverage. What do you think?

**Comment by lwasser** [comment]
Sure - i hear you and think that is wise! It is a big breaking release. i'll continue focus on docstrings / docs and then perhaps tests. I'm happy to continue working in line with what we've been focused on for now!!

**Comment by enadeau** [comment]
Reading this a bit late, but it sounds like a good plan. I've been migrating an app to Pydantic v2 at work so I've gotten quite familiar with the migration guide. I'd be happy to help

**Comment by lwasser** [comment]
hey y'all! what do you think about working on a plan to migrate first? i could create a google doc. we could also focus on the test suite NOW to make the transition to a breaking 2.0 that supports pydantic 2.0 AND deprecates some of the legacy behavior that is causing issues a bit smoother? jonatan we could focus on the test suite while you're super busy first but also work on what needs to migrate in a doc that is then turned into issues / milestones etc. 

Thoughts?

**Comment by enadeau** [comment]
I agree the idea of having a version 2.0 that remove a lot of deprecated stuff and moves to pydantic v2. We should decide if it will still support pydantic v1 or if we'll move to v2 only. I think I'd vote for v2 only since v1 is already in bugfix mode and support will end in less than a year.

I think before we embark on this big project, it would be good to make a big clean-up in the issue. Many can probably be closed. What do you think?
