### ISSUE TITLE
Method to get stream kinda broken.

### ISSUE THREAD

**Issue by enadeau** [stravalib/stravalib#383]
The method to get the streams (`get_activity_streams`, `get_effort_streams`, `get_segment_streams`) seems to not match the schema from strava https://developers.strava.com/playground/#/Streams/getActivityStreams

The types are supposed to be passed as a query argument and not as part of the path. Also, this argument which they call `key` in the schema is required.

I suggest we remove the default of None for those functions and fix the way we build the request. I can take care of it if you agree with the proposed changes.

**Comment by enadeau** [comment]
Actually, most of the function argument seems to not be relevant anymore. It was also pointed out in #367 maybe I can tackle both at once.

Would you prefer removing the argument or deprecating them?

**Comment by jsamoocha** [comment]
Thanks, this sounds good and relates indeed to #367. For backward compatibility (as the existing undocumented arguments still seem to be supported by Strava), can you please add deprecation warnings when using these arguments (you can probably reuse one of the `warn_...` functions in the `exc` module). It will add some additional branching and may require a few more integration tests; please let me know if you need some help with these.

**Comment by enadeau** [comment]
Hi I've started working on it, but I'm confused on how to write tests

My understanding is the strava api mock uses the example from the open api specification to generate a response. Is that right?

My issue might come from some incoherence in strava's spec. For the get activity stream route. The example from the spec is a list of dict while the model is a dict with stream type as key. I also get something matching the model when I make an actual call. https://developers.strava.com/playground/#/Streams/getActivityStreams

The mock is currently returning a list. What would be the best way to get the actual right format out of the mock?

**Comment by enadeau** [comment]
I've pushed the code I've wrote in case it helps you. Should I use response_update to provide a response that matches strava model?

**Comment by jsamoocha** [comment]
> My understanding is the strava api mock uses the example from the open api specification to generate a response. Is that right?

Yes, that is the default. With `response_update` you can update the example from the OpenAPI spec (just as you update a plain Python dict). Alternatively, you can use the `json` or `body` keywords to totally ignore and overwrite the example from the OpenAPI spec.

**Comment by jsamoocha** [comment]
> My issue might come from some incoherence in strava's spec. For the get activity stream route. The example from the spec is a list of dict while the model is a dict with stream type as key. I also get something matching the model when I make an actual call.

I understand your confusion :)

We deviated from the "official" model for reasons of backward compatibility. This final snippet of `get_activity_streams()` is the culprit:

```python
# Pack streams into dictionary
try:
    return {i.type: i for i in streams}  # <-- this is homegrown, and _not_ the Strava response type
except exc.ObjectNotFound:
    return None  # just to be explicit.
```

Please see the inline comment in your PR. I think we'll need to make that change sooner or later, so maybe now would be a good moment to add deprecation warnings. We can commit to your proposed change of the return type later (which will require a major version bump). What do you think?

**Comment by enadeau** [comment]
I think the homegrown thing somehow ended up matching the strava api.

Here's the copy paste of a request I made. We see that the return type if a dict
```
curl -X 'GET' \
>   'https://www.strava.com/api/v3/activities/YYYY/streams?keys=distance&key_by_type=true' \
>   -H 'accept: application/json' \
>   -H 'authorization: Bearer XXXX'
{"distance":{"data":[0.0,0.0,4.9,8.7,12.6,19.7,29.9,40.2,58.5,64.5,70.7,86.9,98.2,133.4,143.8,149.2,156.0,167.0,186.5,201.1,215.3,223.9,241.1,250.7,259.0,267.5,275.5,283.7,291.1,296.8,311.1,318.3,321.0,327.0,332.7,335.4,339.0,342.9,346.5,350.4,354.6,386.1,406.6,415.9,420.8,446.8,484.0,489.7,510.9,515.4,529.3,549.2,553.4,567.0,577.8,582.6,585.6,588.4,599.9,613.3,616.8,618.4,620.0,621.6,623.2,624.8,626.4,628.0,629.6,631.2,632.8,634.4,636.0,637.6,639.2,640.8,642.4,644.0,645.6,647.2,648.8,650.4,652.0,653.6,655.2,656.8,658.4,665.8,673.9,678.2,701.1,714.2,716.2,718.3,725.4,735.0,738.1,742.9,743.8,743.8,744.3,745.4,745.4,745.4,745.4,745.4,745.4,745.4,748.4,749.8,752.0,758.7,768.0,778.2,784.6,796.9,802.8,837.4,892.4,905.2,919.7,928.0,939.6,951.0,963.2,981.4,1006.5,1026.4,1032.9,1045.2,1057.3,1062.3,1071.0,1075.8,1084.8,1106.2,1110.8,1115.6,1120.2,1126.0,1129.0,1131.9,1135.5,1155.9,1173.5,1188.4,1194.9,1236.6,1244.0,1245.1,1248.4,1252.8,1255.9,1259.7,1265.2,1268.5,1274.2,1276.1,1277.9,1285.4,1291.8,1300.3,1319.6,1325.8,1351.3,1357.9,1370.9,1383.3,1388.9,1395.1,1409.3,1436.8,1463.7,1520.0,1531.6,1543.7,1562.1,1574.3,1580.6,1608.2,1615.8,1619.3,1635.8,1640.3,1651.5,1658.1,1661.0,1661.7,1661.9,1665.1,1681.8,1693.3,1698.2,1702.9,1718.7,1724.4,1729.8,1739.5,1754.1,1772.1,1786.1,1799.4,1814.4,1819.4,1839.0,1849.8,1881.1,1897.6,1903.5,1909.1,1920.8,1944.5,1956.6,1980.0,1990.9,2018.9,2024.1,2029.5,2034.5,2039.1,2059.5,2069.4,2080.2,2090.9,2101.5,2106.3,2125.3,2160.0,2169.0,2203.4,2230.2,2235.9,2248.4,2286.0,2325.3,2332.7,2369.9,2383.0,2387.6,2396.3,2400.9,2406.0,2416.9,2427.7,2443.9,2447.7,2450.1,2454.8,2456.6,2458.4,2464.7,2467.9,2471.7,2476.0,2478.9,2481.1,2482.7,2483.9,2493.2,2497.9,2499.7,2503.6,2512.7,2516.7,2520.6,2528.5,2541.7,2573.9,2613.6,2649.3,2658.0,2668.1,2692.1,2703.7,2709.8,2715.7,2732.1,2743.6,2748.6,2783.4,2806.1,2811.9,2814.4,2815.1,2815.5,2821.5,2825.6,2825.6,2825.6,2825.6,2825.6],"series_type":"distance","original_size":291,"resolution":"high"}}
```

The example in [strava's documentation](https://developers.strava.com/playground/#/Streams/getActivityStreams) the example given is
```
[
  {
    "type": "distance",
    "data": [
      2.9, 5.8, 8.5, 11.7, 15, 19, 23.2, 28, 32.8, 38.1, 43.8, 49.5
    ],
    "series_type": "distance",
    "original_size": 12,
    "resolution": "high"
  }
]
```
while the schema looks like the response I got
![image](https://github.com/stravalib/stravalib/assets/12940089/1256a7c9-4fab-4a74-98e9-019c30279a7f)

Look to me like an error in strava's documentation

**Comment by jsamoocha** [comment]
I just tested this, and the exact response depends on whether we provide the `key_by_type` parameter. If you omit it or provide it without value, the response is list-like (as documented by Strava in the example). If you give it _any_ value, the response is dict-like. But this is not something that needs to be exposed through our API.
