### ISSUE TITLE
Unusual behavior with get_activities(before/after)

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#390]
Hey there - can someone else test this code and tell me if they get the expected range of activities as it may be user error ??
i can try to debug but i want confirmation that it isn't user error. Essentially when i try to grab activities from a specified date range

```python
from datetime import datetime
from zoneinfo import ZoneInfo

# Define the Mountain Time Zone
mountain_tz = ZoneInfo("US/Mountain")

# Convert the input strings to datetime objects and associate them with the Mountain Time Zone

# activity jun 12 2022 has comments
after_str = "6/11/2022"
before_str= "6/13/2022"
date_format = "%M/%d/%Y"

before = datetime.strptime(before_str, date_format).replace(tzinfo=mountain_tz)
after = datetime.strptime(after_str, date_format).replace(tzinfo=mountain_tz)

client.get_activities(before=before, after=after)

for a_activity in act:
    activity = a_activity
activity.start_date
# Do you get an activity from 2022?? i don't i get todays activity 
```

Do you get the activity start date that you expect to get? this came up as i'm documenting the comments class elements and kept getting no comments on an activity that should have comments. but now i see it's not the activity i thought i was parsing at all. 

i've tried specifying timezone and not specifying it. 

Digging in more the epoch conversation doesn't return the correct date. 
```
# This is the epoch returned from  `self._utc_datetime_to_epoch(before)`
epoch_time = 1627651200  # Replace this with your epoch time value

# Convert epoch time to datetime object
converted_datetime = datetime.fromtimestamp(epoch_time)

print(converted_datetime)
# returns: 2021-07-30 07:20:00
```

should i keep digging into `_utc_datetime_to_epoch` or is there a specific date format expected here that i'm not providing? i tried initially providing a string and then datetime object.

**Comment by jsamoocha** [comment]
```
date_format = "%M/%d/%Y"
```
This date format is incorrect: for parsing months, you should use lowercase `m` instead of capital `M` (which is for minutes)

Besides that, I cannot reproduce the following:
```
client.get_activities(before=before, after=after)

for a_activity in act:
    activity = a_activity
activity.start_date
```

I'm not sure where `act` comes from. Maybe it was assigned a value elsewhere, from a different call to `get_activities()`?

Finally: are you testing this on the latest version of `master` (including the merged PRs from yesterday)?

**Comment by lwasser** [comment]
> I'm not sure where act comes from. Maybe it was assigned a value elsewhere, from a different call to 
> get_activities()?

oh gosh - i should have taken a break last night. i was fighting with docs and then trying to figure out comments for typing and it was MY MISTAKE. as YES i had defined act earlier and somehow missed assignment in that code (i was testing all sorts of time zone options to see if i could break it). 

one note that i did learn %m is 0-padding so i technically should have had a `%-m/`.. (but it worked without it). I can now tests comments & kudos properly. 

i'm now officially embarrassed about wasting time! i'll close!

**Comment by jsamoocha** [comment]
> i was testing all sorts of time zone options to see if i could break it

This is very good. Next time, try to immediately automate this "trying to break it" behavior in unit tests. 

`@pytest.mark.parametrize()` FTW 😁

**Comment by lwasser** [comment]
@jsamoocha ok! i just wanted you to know that i wasn't ignoring you! when @hozn originally was trying to find a new maintainer team i was really keen to help and knew i could help with docs and infrastructure but was always intimidated by this code base given all of the inheritance! This is why i wanted to start with typing as i suspected it would help me understand that more (and it has!!). 

NOW i think i'm ready to understand the test suite! i have written tests before without an object oriented test suite. but i need to understand this structure next. 

I just got vscode setup to help me use that debugger given tests are failing with this type exercise of model.py. SO i'm going to atleast attempt to understand what's broken now in hopes i can begin to add to our test suite as well. i used to enjoy writing tests but this is a more complex network of objects that i just need to learn :) so... i hope to contrib here too soon!!

**Comment by jsamoocha** [comment]
Haha, all in good time! It took me several years of making tiny contributions until I started to grasp the (now legacy) attributes and models. Really appreciate your recent effort with typing; it will greatly improve the user experience!

**Comment by lwasser** [comment]
@jsamoocha ok that is good to know that it took you time as well! thank you for that! i've been shy about digging into it but typing is really a great way for me to do so. so thank you for the supportive words! i'll continue to dig into the tests and such in hopes that i can help with test suite stuff in the future !! i do enjoy writing tests.
