### ISSUE TITLE
Upcoming changes to API rate limiting

### ISSUE THREAD

**Issue by jsamoocha** [stravalib/stravalib#393]
Strava's new [developer program](https://communityhub.strava.com/t5/developer-knowledge-base/our-developer-program/ta-p/8849) introduces a new "read rate limit", which is for specific endpoints. This means that our existing rate limiters should be modified to:

1. Handle the new headers from a response
2. Execute based on which endpoint is called (which requires a redesign of our rate limiter approach)

It is not clear when Strava will enforce these new rules.

**Comment by jsamoocha** [comment]
Hi all, I want to start working on this and have looked into the existing rate limiters. The redesign should not be too hard: we can use the request method to decide if we're dealing with a read or write request and know which headers to use. As a consequence, the `__call__()` methods of rate limit rules will need an additional argument in their signatures for passing this request method.

There are now three different rate limit rules:

1. `RateLimitRule`: this is a legacy class that totally ignores the limits Strava gives in the response headers. Since clients should abide by the limits imposed by Strava, this class has become unusable, and I propose to remove it.
2. `XRateLimitRule`: this limiter's behavior is to raise exceptions whenever limits are exceeded. However, because the limiter is called _after_ a response is received, it looks like it can never prevent clients from exceeding limits (maybe this explains #288 ?). Additionally, it maintains a state that would become more complex if we added the new read rate limits. For the reasons above and to simplify our codebase, I also propose removing this rate limiter.
3. `SleepingRateLimitRule`: this is the only rate limiter that throttles requests (or, more precisely, sleeps after a response) based on the usage and limits provided by Strava. I propose to use this rate limiter as the default.

Adding the extra argument to the limiters' `__call__()` method will lead to breaking changes for users that have created custom rate limit rules, so this requires a bit of documentation and a minor version bump (1.6?).

Please let me know if the above sounds ok or if I overlooked something. Thanks!

**Comment by yihong0618** [comment]
looks good

**Comment by enadeau** [comment]
I agree with that plan

**Comment by lwasser** [comment]
i'm on board as well! i trust the research you've done here @jsamoocha .thank you!
