### ISSUE TITLE
Testing locally & docs build - use nox instead of make

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#395]
Hey all - i can work on this once i'm done with this typing. i'm using nox locally to run our test suite across versions of python and it's really nice! the one thing i'd have to pin in the functions would be the environment manager we use.

i use conda but i could create a separate function for venv or whatever envt mgr folks here use. this will allow us to test across all versions locally before pushing to github.

it will also allow me to create a dynamic documentation build that will update realtime as we work on docs. 

essentially instead of running something like 

`make -C docs` it would look like
`nox -s docs-live`
`nox -s tests`

we could even have commands to run unit vs other tests and customize as we wish. and it's ALL python configured which makes me happy vs make which feels a bit dinosaur like. 

Is anyone opposed to my doing this in a future pr? i can update the docs and such as well to ensure everyone knows how to use this.

**Comment by enadeau** [comment]
It looks like a great idea!

I've never work with nox. Do you know how what would be the advantage over tox?

> we could even have commands to run unit vs other tests and customize as we wish. and it's ALL python configured which makes me happy vs make which feels a bit dinosaur like.

That sounds interesting! I find it annoying to not be able to run pytest directly and uses all of it's flag to filter test while I'm developing. I'd probably need to first understand why we need the temporary folder that the make file creates in the first place to propose a better solution here?

> i use conda but i could create a separate function for venv or whatever envt mgr folks here use. this will allow us to test across all versions locally before pushing to github.

Knowing nothing about conda myself I'd appreciate if it would also work with other tools (I personally use some mix of venv, pyenv and poetry depending on the project). I can maybe help with that when time comes

**Comment by lwasser** [comment]
hey there @enadeau sure -- so the biggest advantage that i know of (i haven't used tox in a while!!!) is that it's python. so everything we modify will be easier-to-understand for us as python developers vs dealing with a `tox.ini` file and very different semantics. 

> I'd probably need to first understand why we need the temporary folder that the make file creates in the first place to propose a better solution here?

Sure thing. SO.. our project doesn't use a src/ directory (but we could move to that) ... i didn't want to make too many changes when (re) developing the package structure early on. so i stuck with a flat layout. the downside of a flat layout is tests COULD end up being [run on the source files rather than the installed](https://www.pyopensci.org/python-package-guide/package-structure-code/python-package-structure.html#the-src-layout-and-testing) version of our package depending on where you run the tests. In our case -being a pure python package and no real complexity when installing it - we can get away with that. but it's always better to just ensure tests are being run on the installed version just in case we might identify various bugs. 

running things in a new environment should ensure this as well (but i need to look into this a bit). 

> Knowing nothing about conda myself I'd appreciate if it would also work with other tools (I personally use some mix of venv, pyenv and poetry depending on the project). I can maybe help with that when time comes

i'm coming from the science domain so it's really great to use conda when dealing with many scientific applications. (particularly geospatial ones!). but i know that many use venv or some other envt manager. 

what i love about nox is it's easy to create test runs that allow us to utilize our preferred envt managers. OR you can also just use nox's default which is venv.

Venv is great BUT for me - i can create a conda envt with any version of python that i wish without having to download and install a new version. with venv you will have to install python 3.8, 3.9, 3.10 etc to run all of the test suites. nox will actually happily skip any missing version of python on your system leaving you a note that says "oops i can't find python 3.x ... skipping". 

i believe tox will fail loudly if it encounters this but i may be wrong. 

the alternative option here for us would be to move to something like hatch/hatchling. hatch actually has built in nox/tox like behavior. 

but i think what has come up for me is - i really want to be able to run tests across all versions locally rather than pushing to CI and watching things fail :) all of this typing has really made me more aware of some of the differences across python versions that are good to know about locally when building tests / updating code etc!! 

i hope that helps!! my real life job is working in the packaging space (i lead a scientific effort called pyopensci) so what is fun is we are workin on a guide for packaging and i get to test out approaches here (locally) to ensure they play nicely with a real development environment. of course i would never actually make a change here until i am sure it's a good change and also sure everyone on our maintainer team likes / support the approach :) 

my hope is any infrastructure we use makes life easier and simpler for us as maintainers! 
so psyched to have you here helping with all of this!! i think more eyes are always better!

**Comment by lwasser** [comment]
ok final note - i just did some digging into tox for our guide. i think the big diff between tox and nox is the ability to write python code that for us pythonistas, is just easier to understand and maintain :) . there might be other differences but that is the big one that i see.

**Comment by lwasser** [comment]
closing this now that both pr's have been merged including #425 which added the build step using nox!!
