### ISSUE TITLE
ResourceWarning: unclosed <ssl.SSLSocket>

### ISSUE THREAD

**Issue by dave-lawrence-dev** [stravalib/stravalib#406]
After updating to 1.3.3 (from a very old version), I am getting a ResourceWarning with this very simple example:
```#!/usr/bin/python
import stravalib

def test(x):
    return x

client = stravalib.Client(access_token="...")
l = client.get_activities()
a = l.next()
```

```sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('x.x.x.x', 60506), raddr=('18.165.242.69', 443)>```

removing the ```def test``` and the warning goes away. Also seen with:
```
class test:
    def test(x):
        return x
```
but not with
```
class test:
    test = 1
```
requires the ```a = l.next()``` - no problem without it

**Comment by lwasser** [comment]
hey there @dave-lawrence-dev 👋  welcome to stravalib!
I"m having a hard time recreating this. how does your `test(x)` functionrelate to your code example?

test() doesn't interact with the code that you provided in the example above. are there some missing steps perhaps?

i was able to run this code locally with no issues. 

```python
client = stravalib.Client(access_token="...")
l = client.get_activities()
a = l.next()
```

perhaps you can provide a more fully reproducible example to help us identify the issue? and if the code i provided above without the test element still returns an error - perhaps you can provide some environment information to us.

**Comment by dave-lawrence-dev** [comment]
Hi Leah.
That's precisely the problem! The test() function does nothing, is not called and has nothing to do with the execution, but with it defined my sample code gives my the SSL warning. I was able to cut down my original code which defined a class there, to just this function definition to show a minimal example. I can see no logical reason why this should affect operation. Under stravalib 0.10.4 it ran fine, (i've only just upgraded: see issue #405)
enivornment: Ubuntu 22.04 jammy LTS. python 3.10.12, stravalib 1.3.3 - anything else useful?

**Comment by lwasser** [comment]
## Questions

1. what editor are you using to run your code?  
2. how are you running your code? via command line or interactively in an ipython / python terminal? or in a jupyter notebook even?
3. just a sanity check - i just want to make sure that you are  actually populating an access token here (please don't share it here i just want to ensure locally you're populating it) :) `stravalib.Client(access_token="...")`
4. is there any chance you have some sort of firewall or network control that may get in the way of online access? you could potentially test this with code at the bottom of this comment

## Try this:

can you create a new fresh python prompt with no other variables, etc stored in it and try to just run your code:

```
client = stravalib.Client(access_token="...")
l = client.get_activities()
a = l.next()
```

and then this:

## test for internet

```python
import socket

def is_internet_available():
    try:
        # Attempt to connect to a well-known DNS server
        socket.create_connection(("8.8.8.8", 53), timeout=5)
        return True
    except OSError:
        pass
    return False

if is_internet_available():
    print("Internet is available.")
else:
    print("Internet is not available.")
```

i could maybe see this type of general error if you encountered network issues. but i can't wrap my head around why a random isolated function that is not being called would impact stravalib functionality.

**Comment by dave-lawrence-dev** [comment]
1. emacs, but only for editing, not running
2. command line
3. yes, access token in use and working
4. all internet access is working:

"Internet is available."

the example code works, it just gives that SSL warning on exit.

Something weird is happening; it's got to be some timing/race condition
```
$ cat test.py
import stravalib
access_token="..."
client = stravalib.Client(access_token=access_token)
l = client.get_activities()
a = l.next()
$ python ./test.py
[[[ no error reported ]]]
$ python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
[[[ cut and paste each line in ]]]
>>> import stravalib
>>> access_token="..."
>>> client = stravalib.Client(access_token=access_token)
>>> l = client.get_activities()
>>> a = l.next()
>>> ^D
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.1.0.31', 40832), raddr=('18.165.242.71', 443)>
$ 
```

**Comment by lwasser** [comment]
ok thank you for your patience. i am not running ubuntu locally and don't yet have a virtual machine setup for it. Can you print a list of your environment using

> pip list

For us to see versions of things you are running so we can compare? I see youre running python 3.10. 

Then maybe someone else here is running ubuntu that can test this or understands what is happening better than i do. i can't recreate it but i'm on a mac.

**Comment by dave-lawrence-dev** [comment]
Hi, I've just tried moving to python 3.11 and I still get the same weird results.
```Python 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0] on linux```

Here's my pip list: [piplist.txt](https://github.com/stravalib/stravalib/files/12352458/piplist.txt)

It's clearly not to do with the 'test' function be defined, that just happens to trip a race condition or garbage collection oddity. Digging around I found the warning reported by people using other libraries, some quite old, but here's one from a year ago: https://github.com/customerio/customerio-python/issues/87 - might there be a clue in their example? and a call to close() is needed somewhere??

**Comment by lwasser** [comment]
thank you @dave-lawrence-dev ! i think one of our maintainers  with a linux machine will try some further testing to see if they can recreate / identify what is happening! but thank you so much for digging a bit and also providing your system information! this is all super helpful. 

i suspect it's not a python version issue as you mention, given you're using a modern version of python. it could be something where linux needs an explicit "`close()`" but i'll let someone with more experience here step in while continuing to watch the issue in hopes we find a resolution!

**Comment by enadeau** [comment]
Hi I've been trying to replicate this and I can't get the warning running on 3.11.4.
I've run the sample you posted first with the test function.

I can't replicate your environment as some of the package won't install on my machine. For example, `apt-xapian-index==0.49` is not on PyPI.

Can you try to replicate the warning in a clean environment where you only install stravalib? 
If you still it can you then share the requirements.txt and the python version?

**Comment by dave-lawrence-dev** [comment]
Hi,
clean venv was a good idea: I spotted old requests and old urllib3, updating both of these has resolved the problem.
Reviewing the changelogs of these revealed https://github.com/urllib3/urllib3/issues/2970
Which sounds suspiciously like the issue I was seeing. Quite how it was tripped by adding a "null" function I don't understand!

**Comment by lwasser** [comment]
Yay! So glad it was just an envt issue!!
