### ISSUE TITLE
Use ruff for linting

### ISSUE THREAD

**Issue by enadeau** [stravalib/stravalib#427]
I think @lwasser and I would be excited to use ruff as a linting tool. It could replace both flake8 and isort.

It also offers many more check that we could activate.

I've used it on a couple of projects. It works great and is incredibly fast but I think the best feature is that it can autofix many of the errors!

**Comment by lwasser** [comment]
i have a few friends that LOVE ruff! i tried it out in the fall and it was FAST! But I was told it was still a bit "rough" around the edges then. I feel like more and more people are using it now. 

im really excited to play with it here as a tool in our infrastructure!! yay!
