### ISSUE TITLE
BUG: AlpineSki segments not validating (again)

### ISSUE THREAD

**Issue by JohnScolaro** [stravalib/stravalib#432]
### Stravalib version checks

- [X] I have tested this in a new clean environment with only stravalib and core python files.

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/stravalib/) of stravalib.

- [X] I have confirmed this bug exists on the [main branch](https://github.com/stravalib/stravalib) of stravalib.

### What operating system are you seeing the problem on?

Windows

### What version of python or you running?

```python
3.10.12
```

### Reproducible Example

```python
activity = client.get_activity(XXXXXXX, include_all_efforts=True) # Activity must be an AlpineSki with segments
```

### Issue Description

In stravalib v1.4, the issue previously reported here: https://github.com/stravalib/stravalib/issues/368 was re-introducted. Segments can be for activity type "AplineSki" and probably other activities too. Pydantic has an issue with that. It works in v1.3.3.

```
Traceback (most recent call last):
  File "/home/john/code/test_stravalib/test.py", line 18, in <module>
    activity = client.get_activity(8684395669, include_all_efforts=True)
  File "/home/john/code/stravalib/stravalib/client.py", line 619, in get_activity
    return model.Activity.parse_obj({**raw, **{"bound_client": self}})
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 6 validation errors for Activity
segment_efforts -> 0 -> segment -> activity_type
  unexpected value; permitted: 'Ride', 'Run' (type=value_error.const; given=AlpineSki; permitted=('Ride', 'Run'))
segment_efforts -> 1 -> segment -> activity_type
  unexpected value; permitted: 'Ride', 'Run' (type=value_error.const; given=AlpineSki; permitted=('Ride', 'Run'))
segment_efforts -> 2 -> segment -> activity_type
  unexpected value; permitted: 'Ride', 'Run' (type=value_error.const; given=AlpineSki; permitted=('Ride', 'Run'))
segment_efforts -> 3 -> segment -> activity_type
  unexpected value; permitted: 'Ride', 'Run' (type=value_error.const; given=AlpineSki; permitted=('Ride', 'Run'))
segment_efforts -> 4 -> segment -> activity_type
  unexpected value; permitted: 'Ride', 'Run' (type=value_error.const; given=AlpineSki; permitted=('Ride', 'Run'))
segment_efforts -> 5 -> segment -> activity_type
  unexpected value; permitted: 'Ride', 'Run' (type=value_error.const; given=AlpineSki; permitted=('Ride', 'Run'))
```

### Expected Behavior

I expect the activity to be downloaded and parsed/validated successfully by pydantic.

### Your environment

arrow==1.2.3
certifi==2023.7.22
charset-normalizer==3.2.0
idna==3.4
Pint==0.22
pydantic==1.10.9
python-dateutil==2.8.2
pytz==2023.3
requests==2.31.0
six==1.16.0
stravalib==1.4
typing_extensions==4.7.1
urllib3==2.0.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by enadeau** [comment]
I've been able to replicate the bug with a hiking activity that contains segments. 

I'll take a look at your PR and also try to add a test for that. We definitely don't want to introduce this bug a third time!
