### ISSUE TITLE
BUG: Failed action - stravalib model check

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#438]
https://github.com/stravalib/stravalib/actions/workflows/check-strava-api.yml

### Issue Description

This is related to several failing builds of the strava_model.py action. it can't seem to find the swagger.json file. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jsamoocha** [comment]
That swagger.json file is there on Strava, but the job cannot access it (after it is downloaded?). Maybe it has something to do with recent changes to our build tooling?

**Comment by lwasser** [comment]
Yes!! This is closed now but I suspected that when I saw the point ot
failure was related to finding a file! I broke it.  I just missed looking
at this build closely when I made that big change.  I should have tested
this workflow manually prior to merging! I know now for any future changes.
BUT I don't see us making any directory level changes anytime soon either!
