### ISSUE TITLE
BUG: get_activity_photos() seems broken

### ISSUE THREAD

**Issue by fortysix2ahead** [stravalib/stravalib#443]
### Stravalib version checks

- [X] I have tested this in a new clean environment with only stravalib and core python files.

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/stravalib/) of stravalib.

- [x] I have confirmed this bug exists on the [main branch](https://github.com/stravalib/stravalib) of stravalib.

### What operating system are you seeing the problem on?

Mac

### What version of python or you running?

```python
3.9
```

### Reproducible Example

```python
photos = client.get_activity_photos( some_activity_id_with_photos )
for p in photos:
  print( p )
```

### Issue Description

The simple example above results in the following exception:
```
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "Projects/com.github.tracs/venv/python39/lib/python3.9/site-packages/stravalib/client.py", line 2038, in __next__
    return self.next()
  File "Projects/com.github.tracs/venv/python39/lib/python3.9/site-packages/stravalib/client.py", line 2044, in next
    self._fill_buffer()
  File "Projects/com.github.tracs/venv/python39/lib/python3.9/site-packages/stravalib/client.py", line 2006, in _fill_buffer
    new_entity = self.entity.parse_obj(
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ActivityPhoto
sizes -> 1800
  value is not a valid float (type=type_error.float)
```

1800 is the default value which is obviously a valid float. The method takes `size` of type int as a parameter, but no matter what value is fed into the call, the exception stays the same.

### Expected Behavior

Getting the photos ...

### Your environment

appdirs==1.4.4
arrow==1.3.0
attrs==23.1.0
Babel==2.13.0
beautifulsoup4==4.12.2
bottle==0.12.25
cattrs==23.1.2
certifi==2023.7.22
chardet==5.2.0
charset-normalizer==3.3.0
click==8.1.7
click-shell==2.1
colorama==0.4.6
confuse==2.0.1
dataclass-factory==2.16
DateTimeRange==2.2.0
exceptiongroup==1.1.3
fs==2.4.16
geojson==3.0.1
ghp-import==2.1.0
gpxpy==1.5.0
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
Jinja2==3.1.2
lxml==4.9.3
Markdown==3.5
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mbstrdecoder==1.1.3
mdurl==0.1.2
mergedeep==1.3.4
mkdocs==1.5.3
mkdocs-click==0.8.1
mkdocs-material==9.4.5
mkdocs-material-extensions==1.2
oauthlib==3.2.2
orjson==3.9.9
packaging==23.2
paginate==0.5.6
pathspec==0.11.2
Pint==0.22
platformdirs==3.11.0
pluggy==1.3.0
ply==3.11
pydantic==1.10.9
Pygments==2.16.1
pymdown-extensions==10.3
pytest==7.4.2
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
pyyaml_env_tag==0.1
regex==2023.10.3
requests==2.31.0
requests-cache==1.1.0
requests-oauthlib==1.3.1
rich==13.6.0
rule-engine==4.1.0
six==1.16.0
soupsieve==2.5
stravalib==1.5
tcxreader==0.4.4
tomli==2.0.1
typepy==1.3.2
types-python-dateutil==2.8.19.14
typing_extensions==4.8.0
tzlocal==5.1
url-normalize==1.4.3
urllib3==2.0.6
watchdog==3.0.0
zipp==3.17.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jsamoocha** [comment]
Hi, thanks for reporting this! It should be fixed now and be generally available in the next release.

Please be aware that `get_activity_photos()` is an undocumented API method that may stop working without warning.

**Comment by fortysix2ahead** [comment]
You mean "undocumented" by Strava? If yes, is there an official API to get photos of an activity?

**Comment by jsamoocha** [comment]
There is no official endpoint to retrieve photos. See https://developers.strava.com/docs/reference/.
