### ISSUE TITLE
BUG: Unable to remove My API Application

### ISSUE THREAD

**Issue by netsrikc** [stravalib/stravalib#452]
### Stravalib version checks

- [X] I have tested this in a new clean environment with only stravalib and core python files.

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/stravalib/) of stravalib.

- [X] I have confirmed this bug exists on the [main branch](https://github.com/stravalib/stravalib) of stravalib.

### What operating system are you seeing the problem on?

Mac

### What version of python or you running?

```python
Not using python, only using Thunder Client (VSC extension)
```

### Reproducible Example

```python
Steps to reproduce:

1. Call https://www.strava.com/oauth/deauthorize using my access token, obtained from the My API application page
2. Received a 200 status with the same access token attached to the request
3. Navigate to My Apps page

Expected:
To not see the api application on the list, per docs here: https://developers.strava.com/docs/authentication/ (Deactivation section)

Observed:
- I am still seeing the same api application on the "My Apps" list.
- The application is still shown on the "My API Application" page, but with a new access token

Alternatively, I just want to be able to get a new access token with new permissions provisioned, but I cannot find a place to do so.
```

### Issue Description

I can't seem to remove my API Application that I have created a long time ago, nor can I request a new token with new permissions associated with it.

### Expected Behavior

See Reproducible Example section.

### Your environment

I am using Thunder Client (A VSC extension) to make this network call.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lwasser** [comment]
hey @netsrikc 👋 welcome to stravalib. 

i am not familiar with the thunderbird extension for vscode. but it sounds like you are not using python / stravalib to hit the API so this might be a API issue rather than a stravalib issue. can you please clarify how this issue relates to the stravalib python package?

**Comment by netsrikc** [comment]
Hello! Sorry I was under the wrong impression that this is the right place to leave this bug - is there a place where I can file a bug for the API?

**Comment by jsamoocha** [comment]
Hi, you could try https://communityhub.strava.com/t5/developers/ct-p/developers.

**Comment by lwasser** [comment]
@netsrikc please don't apologize!! we understand that issues come up with the API and sometimes it's hard to figure out where to post questions! i'm going to close this issue now, however please feel free to reopen if you do find there is something we can help you with related to stravalib! best of luck with troubleshooting the API issues!! i hope the strava community helps you!
