### ISSUE TITLE
BUG: Validation error when an old activity has a type of WaterSport

### ISSUE THREAD

**Issue by epic-climber** [stravalib/stravalib#460]
### Stravalib version checks

- [X] I have tested this in a new clean environment with only stravalib and core python files.

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/stravalib/) of stravalib.

- [ ] I have confirmed this bug exists on the [main branch](https://github.com/stravalib/stravalib) of stravalib.

### What version of python or you running?

```python
3.11.7
```

### Reproducible Example

```python
client.get_activities(after, before)
```

### Issue Description

Ran into an activity from 2017 with `"WaterSport"` as the activity type and `"Canoeing"` as the sport type. `"WaterSport"` is not valid in [strava model](https://developers.strava.com/docs/reference/#api-models-ActivityType), but looks like it used to be.
Iterating over `client.get_activities` hits a `ValidationError` when `BatchedResultsIterator` fetches a page of activities, so the entire batch fails and there isn't a good way to skip just the bad activity.

### Expected Behavior

Need to not fail when hitting these old activities. My current workaround is to change the list in `stravalib.strava_model.ActivityType`

### Your environment

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lwasser** [comment]
i just submitted this issue - https://github.com/stravalib/stravalib/issues/461 which proposes a new release to accomodate this and other issues reported around this. i think it's not addressed fully until we perform a release because installing from a commit or a branch is a bit sketch for folks developing tools and apps!  lemme know what y'all think!

**Comment by lwasser** [comment]
@epic-climber the release is out! please reopen or create a new issue if you have issues with this still!
