### ISSUE TITLE
New release: stravalib 1.6

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#461]
We current have a lot of singificant bugs that multiple people have reported addressed in the main branch. however, we also have [this commit](https://github.com/stravalib/stravalib/commit/c2561b6771fa88c5f9add1cf1b9807c4b4da3171) which is seems like was merged prematurely. (which is ok). 

I suggest that we create a new release for stravalib 1.6 and at the same time, back track on the merged commit above moving the repo to the [commit change here](https://github.com/stravalib/stravalib/commit/f8761e708215f2aba2a6d271eeb0070e57bdb01b) submitted by @jsamoocha . In doing this, we could create a branch off of main to ensure we have a full copy of that history. and i'd just undo the existing commit - either with a reversal PR that undos it or a history rewrite. 

whatever you all want. 

i'd then release 1.6 
i can easily do all of this in the upcoming 3 days if @jsamoocha @yihong0618  @enadeau are on board with the plan. that way this bug that has been submitted a few times including [here](https://github.com/stravalib/stravalib/issues/460) is addressed. what do you all think?

**Comment by lwasser** [comment]
if y'all are ok with my plan i'll then remove the test suite as discussed and we can incorporate that into a later release since that doesn't impact our users at all.

**Comment by jsamoocha** [comment]
This sounds great to me. As some people may have already pulled from `main`, removing the last commits using revert may be cleaner.

**Comment by lwasser** [comment]
i agree @jsamoocha the reversal leaves a much cleaner history! [i just opened this pr](https://github.com/stravalib/stravalib/pull/462) once we merge i'll create a release (i can do it later today).

**Comment by lwasser** [comment]
closing this via #463 and the latest release is now available from pypi - version 1.6
