### ISSUE TITLE
Infrastructure cleanup: remove requirements.txt in liue of optional.dependencies table in pyproject.toml

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#466]
After learning more about [dependency declaration in modern packaging](https://www.pyopensci.org/python-package-guide/package-structure-code/declare-dependencies.html), I am realizing that we could be using the pyproject.toml to declare all dependencies (test, development, docs etc) rather than having a separate requirements file that houses everything.

Doing this would allow people to only install subsets of deps that they wish OR they could choose to install everything . This would cleanup our noxfile steps a bit as well. 

I think we could also consolidate the nox docs static build with the live build into a single function.

so i propose a PR that just is a smallish cleanup pr that would

- [ ] Add dependencies as groups in an optional.dependencies table in our pyproject.toml file
- [ ] cleanup the nox file to then install using that approach + pip 
- [ ] Merge the noxfile docs live and docs static build into one with a flag to choose static vs live build. 

this is just a small effort towards easier maintenance (fewer files, less noxfile code etc)

**Comment by enadeau** [comment]
I agree I think we should use the opportunity to pin dependencies a bit better. 

First example that comes to mind is pydantic==1.10.9  that should probably be relaxed to <2 and maybe until we add support for v2.

Maybe the dev dependencies should be pinned to specific version to avoid inconsistency in CI and between devs

**Comment by lwasser** [comment]
oh right! this is the one time that we should implement an upper bounds pin isn't it? i will try to prioritize this next. that upper bound pin is a really important example @enadeau thank you. i didn't even think about that. it's probably worth a small release just to fix that for users.
