### ISSUE TITLE
Time for Stravalib Release 1.7 ?

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#483]
Hey @stravalib/stravalib-maintainers Our changelog is starting to pile up with fixes. What do you think about a new release 1.7?

We can either include the most recent pr #358  or not depending on how complex the fix is there. 

Thoughts?

**Comment by lwasser** [comment]
ok friends. i'm going to go ahead and prepare a release. i think it's time given the state of our changelog.

**Comment by enadeau** [comment]
Nice sorry didn't reply. Life is quite busy at the moment. Let's go for a release of there's a lot to get out.

**Comment by lwasser** [comment]
@enadeau please do not apologize! i totally understand busy lives! we are all volunteers here ✨ it's just a very rainy dark chilly day here so good timing for me to work on a bit of open source stuff :) thank you for responding!!

**Comment by lwasser** [comment]
things uploaded and v1.7 is now live! i found a few bugs in our publish pypi workflow and fixed them. the build has been failing for a few weeks and i missed it! all is good now. thanks everyone!
