### ISSUE TITLE
ENH: Drop Python 3.9 support + Add python 3.12 support

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#487]
Following #301 and #486  
Python 3.8 was released 4.5 years ago adn security support for it [ends in october 2024](https://endoflife.date/python). 
Following the Numpy standards they recommend dropping support for python versions after ~3 years. I think it is justified if others are on board to drop support for 3.9 at this time and to add support for python 3.12 which many people are migrating to now and it is the currently active supported version of Python

Please let me know what ya'll think.

**Comment by enadeau** [comment]
I'm on board with that

**Comment by lwasser** [comment]
ok great. i see a thumbs up from Jonatan as well. i'll work on a PR
