### ISSUE TITLE
Stravalib2.0 -> Remove BackwardCompatibilityMixin

### ISSUE THREAD

**Issue by jsamoocha** [stravalib/stravalib#498]
- [x] Remove this mixin to prevent typing issues such as #437.
- [x] Remove all `_field_conversions` from model classes.

The "enhanced" fields will get the same (parent) type as the overridden fields from the generated strava model.
This will make several tests fail, which will be resolved in other issues.

**Comment by lwasser** [comment]
thank you for opening all of these issues! this is much more organized than how i was approaching things. i'm taking notes!
