### ISSUE TITLE
Stravalib 2.0 -> For every endpoint, we should check the Strava API docs for the correct return type

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#506]
For every endpoint, we should check the Strava API docs for the correct return type

_Originally posted by @jsamoocha in https://github.com/stravalib/stravalib/pull/505#discussion_r1597580080_
            
I'm just turning this into an issue so we remember to do it. i'm happy to help with this when we are ready to do it.

**Comment by jsamoocha** [comment]
Copying this list from #250 for reference. We can let one another know what we're working on by checking the boxes below:

- [ ] /athletes/{id}/stats (GET)
- [ ] /athlete (GET)
- [ ] /athlete (PUT)
- [ ] /athlete/zones (GET)
- [ ] /segments/{id} (GET)
- [ ] /segments/starred (GET)
- [ ] ~~/segments/{id}/starred (PUT)~~ - NOT IMPLEMENTED AT ALL
- [ ] /segment_efforts (GET)
- [ ] /segments/explore (GET)
- [ ] /segment_efforts/{id} (GET)
- [ ] /activities (POST)
- [ ] /activities/{id} (GET)
- [ ] /activities/{id} (PUT)
- [x] /athlete/activities (GET)
- [ ] /activities/{id}/laps (GET)
- [ ] /activities/{id}/zones (GET)
- [ ] /activities/{id}/comments (GET)
- [ ] /activities/{id}/kudos (GET)
- [ ] /clubs/{id} (GET)
- [ ] /clubs/{id}/members (GET)
- [ ] /clubs/{id}/admins (GET)
- [ ] /clubs/{id}/activities (GET)
- [ ] /athlete/clubs (GET)
- [ ] /gear/{id} (GET)
- [ ] /routes/{id} (GET)
- [ ] /athletes/{id}/routes (GET)
- [ ] /routes/{id}/export_gpx (GET)
- [ ] /routes/{id}/export_tcx (GET)
- [ ] /uploads (POST)
- [ ] /uploads/{uploadId} (GET)
- [ ] /activities/{id}/streams (GET)
- [ ] /segment_efforts/{id}/streams (GET)
- [ ] /segments/{id}/streams (GET)
- [ ] /routes/{id}/streams (GET)

**Comment by lwasser** [comment]
all items in the list for this issue have been checked. I am going to close this as complete. please reopen if there are things i'm missing!!
