### ISSUE TITLE
ENH: implement `athlete/zones` GET client method

### ISSUE THREAD

**Issue by jsamoocha** [stravalib/stravalib#508]
### Feature Type

- [X] Adding new functionality to stravalib

- [ ] Changing existing functionality in stravalib

- [ ] Removing existing functionality in stravalib

### Problem Description

This endpoint is not implemented

### Feature Description

Implement a client method

### Alternative Solutions

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lwasser** [comment]
@jsamoocha do you want to implement this as a part of our 2.x release? i'm just checking in on what is left in our list to do.

**Comment by jsamoocha** [comment]
This is not strictly necessary for the 2.0 release. We can leave it as a TODO for later.

**Comment by lwasser** [comment]
perfect. thanks
