### ISSUE TITLE
Stravalib 2.0 -> Replace invariant by covariant container types

### ISSUE THREAD

**Issue by jsamoocha** [stravalib/stravalib#510]
This should resolve various typing issues we're now suppressing that are due to overriding invariant container types. See https://mypy.readthedocs.io/en/stable/generics.html#variance-of-generics. In practice, our model classes should use `Sequence` or `Mapping` container type instead of, e.g, `list` or `dict`. There's an issue in the bot repo to modify the code generator in order to have covariant container types in the strava model as well.

**Comment by lwasser** [comment]
i am going to take a stab at this next @jsamoocha if that sounds good to you. i've wanted to also go through and update types (dropping Optional even tho i really like the expressiveness of Optional) so i could do this in two pr's. i'll start with the [bot repo pr first](https://github.com/stravalib/strava_swagger2pydantic/issues/13).

**Comment by lwasser** [comment]
[pr here](https://github.com/stravalib/strava_swagger2pydantic/pull/14/files)

I am thinking about also implementing the use Union = True. this would then require updating ALL instances of optional throughout our code which would create merge conflicts potentially.  so i'll do this in pieces and will coordinate with you @jsamoocha for when you are not working on things before implementing that change!

**Comment by lwasser** [comment]
@jsamoocha i started to play with this in #530 do we want to convert ALL list elements to Sequence or should we do it strategically? I understand generally how this works and the value of Sequence relative to our typing issues. However I wasn't sure if we wanted to migrate list /dict universally --> Sequence or not.

**Comment by lwasser** [comment]
are there other pieces to this that need to be implemented @jsamoocha or can we close this issue now?

**Comment by jsamoocha** [comment]
This is all done 👍
