### ISSUE TITLE
Replace `pydantic.datetime_parse()` with `dateutil.parser.parse()`

### ISSUE THREAD

**Issue by bmeares** [stravalib/stravalib#521]
To accelerate a Pydantic 2 migration, we should be able to drop-in replace the use of `pydantic.datetime_parse()` with `dateutil.parser.parse()`.

I can put together a PR in the next week or so if you would like.

**Comment by jsamoocha** [comment]
Hi, I think this piece of work was somewhere on our TODO list, so any contribution is highly appreciated! We're now working on a `pydantic-v2` branch, so please base your branch on that.

(@lwasser weren't you mentioning issues somewhere about parsing datetimes? I couldn't find any open issue.)

**Comment by bmeares** [comment]
@jsamoocha this was the [comment](https://github.com/stravalib/stravalib/pull/491#issuecomment-2081722030) from @lwasser about datetime parsing. I had clicked on `Reference in New Issue` thinking GitHub would include a link, oops!

I'll base off of `pydantic-v2`, thanks👍

**Comment by lwasser** [comment]
hi there @bmeares 👋🏻 welcome to stravalib!! ✨ 

A pr would be awesome here - yup Jonatan - they've got it right! My pr was just adding some tests given i knew we needed to rewrite and there were no existing tests / gaps in our coverage via code cov! feel free to use what i started in terms of tests or rewrite OR I can close that pr if things move in a different direction and we need different tpes of tests! 

i'm working on the end point checks right now!

**Comment by jsamoocha** [comment]
One reminder: since this branch `pydantic-v2` is WIP, you can ignore mypy typing issues. We'll fix these later.
