### ISSUE TITLE
🙌🏻 Please Test 🙌🏻  Pre-release candidate for stravalib v2 // support for pydantic v2

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#544]
We currently have a significant amount of work compiled in the pydantic-v2 branch that is generally working but i presume users will find bugs. 

Are there any core features / fixes / checks that we want to do before cutting a pre-release from the pydantic-v2 branch? this will not impact current pypi users but it will allow folks to test out the changes via the pre-release prior to us cutting a full 2.x release.

We could then spend a bit of time looking at tests and final doc cleanup as folks tests things out. 
i have bandwidth now that i'm back to work on things again. 

What do you think?

**Comment by jsamoocha** [comment]
Let's make the release candidate and test it!

**Comment by lwasser** [comment]
Done!! wow that feels good. our last release was in april 🚀 

✅ it's on pypi now - 
✅ i also created a discussion for the release candidate

if anyone is following this please test out the 2.0 pre release on [pypi here](https://pypi.org/project/stravalib/2.0.0rc0/). 

stravalib 2.0 can be tested by installing from pypi as follows:

`pip install stravalib==2.0.0rc0` 

we welcome any and all feedback in our [discussion channel here](https://github.com/orgs/stravalib/discussions/551).

**Comment by lwasser** [comment]
ok i am going to close this as well. we will cut a new release tomorrow. everything is in place for the release to be published at this point!!
