### ISSUE TITLE
Release stravalib 2.x

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#553]
Hi all - now that our release candidate has been out for 2 weeks, i think it might be time to release stravalib 2.0. @jsamoocha any thoughts on that?

if we do so the tasks would be

- [x] review / merge #548 - this is just a small update to bump to typing for python 3.10+
- [ ] update the changelog
- [ ] Create a release!!

after that we can focus on tweaking docs and such. thoughts? it's been quiet here so it seems like either people aren't using the release candidate OR they have used it and it's good enough. please let me know what you think!

**Comment by jsamoocha** [comment]
Let's continue with the release. Before merging `pydantic-v2` into `main,` let's see if we can add the small PR that will result from #552.

**Comment by lwasser** [comment]
@jsamoocha I'm ok with that but it might be more efficient to just create a release. 

 I'm happy to create a patch release when #533 comes in as a pr. It would be a quick and easy patch to make. 

Suggestion: lets  give that pr a few days to.come in. Lets also plan to release 2.0 on Monday.

That way we are not pushing the new release out too much in case the pr takes more time than expected.
Thoughts?

**Comment by jsamoocha** [comment]
Sound perfect. The PR resulting from #552 can be merged later without problems as it will be based on the pydantic-v2 branch.
