### ISSUE TITLE
Docs are failing - banner migration link is broken

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#562]
I had fixed the docs but they seem to be broken again so our online docs are not in sync with the current docs.  This hopefully is a small fix!

**Comment by jsamoocha** [comment]
Docs seem to be built now, but I get a 404 on the 2.0 migration guide (https://stravalib.readthedocs.io/whats-new/stravalib-2.html)

**Comment by lwasser** [comment]
oh that's interesting. This is specific to the top bar link. the [what's new link here](https://stravalib.readthedocs.io/en/latest/whats-new/stravalib-2.html) from the top nav works. let's leave this open and i'll look into that. it's resolving without including the en/latest in read the docs.

**Comment by lwasser** [comment]
@jsamoocha i think this is fixed now after testing! if it's not on your end please let me know  and we can reopen!
