### ISSUE TITLE
ENH: Add created_at to DetailedAthlete

### ISSUE THREAD

**Issue by claytonneal** [stravalib/stravalib#566]
### Feature Type

- [X] Adding new functionality to stravalib

- [ ] Changing existing functionality in stravalib

- [ ] Removing existing functionality in stravalib

### Problem Description

Apps written on Strava want to ensure that the account they are being authorised to access isnt a spam account. One such measure is checking the age of the account.

### Feature Description

In the API docs: https://developers.strava.com/docs/reference/#api-models-DetailedAthlete
The DetailedAthlete response containts "created_at", however this field is not in the python model class for DetailedAthlete
Can this be added?

### Alternative Solutions

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by claytonneal** [comment]
The typescript wrapper has it: https://github.com/amorgulis/strava-typescript-api/blob/master/src/models/detailed-athlete.ts

**Comment by enadeau** [comment]
Hi, 

As far as I can see the field is actually present on the DetailedAthlete model https://github.com/stravalib/stravalib/blob/18c92443e8ddfe3aa536e0e9b2881dfb84ce7aaf/src/stravalib/strava_model.py#L683
It is actually on the SummaryAthlete model that is a subclass of DetailedAthlete.

Could you give a code sample of how you're retrieving an DetailedAthlete that does not have the created_ad field?

**Comment by claytonneal** [comment]
Ok my bad, feel free to close, i was scanning the code rather than using an IDE! thanks for the feedback
