### ISSUE TITLE
Some fields have different types in stravalib.model.SummaryActivity  and stravalib.model.DetailedActivity

### ISSUE THREAD

**Issue by enadeau** [stravalib/stravalib#570]
### Discussed in https://github.com/orgs/stravalib/discussions/568

<div type='discussions-op-text'>

<sup>Originally posted by **jlelong** August 29, 2024</sup>
Thanks a lot for library!

Fields related to elevation, duration and speed have a float type in `SummaryActivity` but more precise types in `DetailedActivity` such as `DistanceType`, `ElevationType`, VelocityType`. Could it be possible to use the same types in both `SummaryActivity` and `DetailedActivity` to make sure  a `DetailedActivity` can be cast to a `SummaryActivity`?

I would like to be able to use a `DetailedActivity` when a `SummaryActivity` is expected but I cannot figure out how to do it.</div>

**Comment by lwasser** [comment]
@all-contributors add @jlelong for bug
