### ISSUE TITLE
BUG: average_cadence is not present in SummaryActivity

### ISSUE THREAD

**Issue by david-pacheco-zwift** [stravalib/stravalib#594]
### Stravalib version checks

- [X] I have tested this in a new clean environment with only stravalib and core python files.

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/stravalib/) of stravalib.

- [X] I have confirmed this bug exists on the [main branch](https://github.com/stravalib/stravalib) of stravalib.

### What version of python or you running?

```python
3.10.12
```

### Reproducible Example

```python
when calling activities = strava_client.get_activities(after=after) it returns a list of SummaryActivity objects. However, this class now does not contain the average_cadence attribute that was present before and is returned by Strava API when calling Get Activities
```

### Issue Description

when calling activities = strava_client.get_activities(after=after) it returns a list of SummaryActivity objects. However, this class now does not contain the average_cadence attribute that was present before and is returned by Strava API when calling Get Activities

### Expected Behavior

The SummaryActivity object should contain the average_cadence attribute with the retuned value from. Strava

### Your environment

<details>

Replace this line with the output of pip or conda list.

</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jsamoocha** [comment]
Hi!

Thanks for reporting this. A PR with fixes is on its way!

**Comment by lwasser** [comment]
hey @david-pacheco-zwift, I'll be making a new release in the next week!
